avajs/ava

- readme.md
> Grammar fix

- index.js
- lib/test.js
- package.json
PR title pretty much says it all :D 
Related to #24
> add setImmediate() shim via set-immediate-shim module

- test/test.js
To ensure that runner is inherit `EventEmitter`.
> Add test on runner test event

- lib/babel.js
> Babelify only test files

- lib/babel.js
> use asyncToGenerator transform

- cli.js
> Display error message when there are no test files

- test/fork.js
Cover `fork.js` with basic tests (#54).
> Add some tests on fork.js

- lib/fork.js
- test/fixture/process-cwd.js
- test/test.js
> Set process.cwd() to a test's directory

- cli.js
- lib/runner.js
- test/test.js
> Don't display test title, if there's only one anonymous test

- lib/test.js
- package.json
> Would be nice not depending on a git repo as it causes problems for people without git.
I realized i didn't have git on my Windows VM.
> Use co-with-promise instead of git url in package.json

- test/runner.js
100% Statement, function and line coverage for lib/runner.js. 
Covers the case where Runner is not called with "new".
> Improved test coverage for runner.js (issue #161)

- index.js
- lib/babel.js
- lib/globals.js
- lib/test.js
- package.json
- test/fixture/fake-timers.js
- test/fork.js
> Guard against clock manipulation by fake timer libraries. Fixes #128.

- lib/runner.js
- lib/test.js
- readme.md
- test/fixture/long-running.js
- test/fixture/loud-rejection.js
- test/fixture/serial.js
- test/observable.js
- test/promise.js
- test/test.js
> Rename test.async to test.cb

- lib/test.js
- test/test.js
> Add ability to skip individual assertions. Fixes #9.

- readme.md
As promised in <https://github.com/sindresorhus/ava/issues/185#issuecomment-161093243>.
> document nyc's source map support

- contributing.md
- maintaining.md
- readme.md
Fixes #167.
// @markthethomas @Whoaa512 @SamVerschueren
> add contributing guidelines - fixes #167

- package.json
This cuts the time for `npm test` almost in half!
> use latest nyc and caching

- readme.md
> Document skippable assertions.

- code-of-conduct.md
- contributing.md
Adapted from http://contributor-covenant.org/
This is important to have.
> Add Code of Conduct

- cli.js
- package.json
> Default to the verbose reporter on CI servers. Fixes #435

- readme.md
fly-ava is ava plugin for [fly](https://github.com/bucaran/fly)
https://github.com/pine613/fly-ava
Thank you
> add fly-ava plugin

- lib/runner.js
- package.json
See https://github.com/jamestalmage/option-chain
Feedback on the API appreciated
> Move method chaining to an external module (`option-chain`)

- docs/recipes/code-coverage.md
> Docs : Improve Code Coverage for Windows

- docs/recipes/code-coverage.md
Easier to review here:
https://github.com/jamestalmage/ava/blob/fix-coverage-recipe/docs/recipes/code-coverage.md
> Improve the coverage recipe

- index.js
- lib/fork.js
- lib/reporters/mini.js
- lib/reporters/verbose.js
- lib/runner.js
- lib/test-worker.js
- test/api.js
- test/reporters/mini.js
- test/reporters/verbose.js
- test/runner.js
> Send less data

- lib/sequence.js
> Clean up sequence

- readme.md
> Fix babel-register in documentation

- lib/concurrent.js
- test/concurrent.js
> Clean up concurrent

- lib/reporters/tap.js
- test/reporters/tap.js
> Fix failed line missing from TAP output

- index.js
- lib/runner.js
- lib/test-collection.js
- test/test-collection.js
This PR cleans up lib/test-collection.js and a part of my cleaning up set of PRs.
I still don't like it a lot, but it's a step forward.
> Clean up test-collection

- docs/recipes/browser-testing.md
- docs/recipes/typescript.md
For the 2 new recipes (typescript and browser testing)
> Docs : Links to French translation

- lib/watcher.js
> Fix linting error

- docs/recipes/browser-testing.md
- docs/recipes/typescript.md
For the 2 new recipes (typescript and browser testing)
> Docs: Links to Russian translation

- docs/recipes/watch-mode.md
> Docs: Link to French translation for watch mode

- docs/recipes/watch-mode.md
> Docs: Add link to russian translation for watch mode

- docs/recipes/watch-mode.md
- lib/watcher.js
- package.json
- test/watcher.js
This reverts commit 5f109b6c026911c94b57e867bd0331af146023a4.
See discussion in <https://github.com/sindresorhus/ava/pull/658#issuecomment-198987516>.
> Revert "rerun tests using "r" key"

- lib/runner.js
- test/runner.js
Fixes #697.
Let me know if a better error message helps!
> Make `test.todo(title, fn)` produce a failure

- docs/recipes/babelrc.md
Link to french translation for new recipe : babelrc
> Docs: Link to French translation for babelrc recipe

- docs/recipes/watch-mode.md
- lib/watcher.js
- test/watcher.js
> Watch mode always runs all exclusive tests

- lib/enhance-assert.js
> Add strict mode in `enhanced-assert.js`

- contributing.md
- maintaining.md
Document our [issue labels](https://github.com/sindresorhus/ava/labels) in the contributing and maintaining guides.
> Document issue labels

- lib/reporters/tap.js
- test/reporters/tap.js
> Put failing TAP test title in the second line

- lib/enhance-assert.js
just a pr to fix #681 to get more descriptive logs (found out from power-assert-js/power-assert#41)
> increase power-assert's maxDepth option to 3. Fixes #681

- docs/recipes/babelrc.md
Better language, and more thorough linking to Babel's config documentation
I think this comes pretty close to fixing #447
> Improve babelrc recipe

- readme.md
> Docs: Remove trailing comma to make JSON valid

- test/visual/run-visual-tests.js
The issue linked in the comment has been fixed, to the comment is not needed anymore :)
> Remove unneeded eslint-disable comment

- docs/recipes/react.md
Just adding the french translation to the React recipe.
> Adding french translation link to the React recipe

- readme.md
Thought people may find this chat helpful.
> add podcast episode to links

- readme.md
Hi. I've changed my GitHub username.
Thank you.
> Update the fly-ava repository URL

- bench/compare.js
Added standard deviation to the stats reported when benchmarking. For #724.
> Added std dev to benchmark stats

- package.json
- profile.js
- test/profile.js
> Fix profiling script and add some tests for it.

- docs/recipes/browser-testing.md
> Fix typo in `browser-testing` recipe

- api.js
> Remove 'ready' event from API

- readme.md
> doc: add korean translations link

- lib/assert.js
- lib/enhance-assert.js
- readme.md
- test/assert.js
> add t.notRegex

- readme.md
To improve documentation, add a link to the recipe in the section Typescript of the README.md file (as the recipe babelrc in the previous paragraph)
> Add link to Typescript recipe

- docs/common-pitfalls.md
* Fix link to issue 751
* Add link to french translation
> Docs: Fix link to issue 751 and add link to french translation

- docs/recipes/jspm-systemjs.md
Add link to french translation of JSPM recipe
> Docs: Add link to french translation of JSPM recipe

- lib/assert.js
- test/assert.js
> Remove t.doesNotThrow - fixes #850

- docs/recipes/browser-testing.md
> Docs: Add link to spanish translation of 'Browser testing'

- contributing.md
Links to https://medium.com/@vadimdemedes/making-your-first-contribution-de6576ddb190 in contributing.md.
Not a self promotion, requested by @sindresorhus :)
> Link to "making first contribution" blog post

- readme.md
Fixes #1129 
Also bumped the expected version in the `package.json`
> Recommend Yarn for installation

- package.json
- readme.md
Noticed that @vadimdemedes changed his github name :).
> fix vadimdemedes github link

- test/assert.js
Per https://github.com/avajs/ava/commit/973624d0d13f291901c9bd324eddc4a380629505#commitcomment-19969925
> Remove duplicate test

- readme.md
Just a minor change that keeps the readme up to date.
> Update expected package.json version in readme

- package.json
Fixes #1083.
Will land when CI passes.
> Bump ava-files

- lib/caching-precompiler.js
> Add `powerAssert` status to package salt

- profile.js
> Resolve relative modules in profile.js just like with CLI/API

- docs/specs/001 - Improving language support.md
> Docs: Add link to french translation of RFC001

- docs/recipes/watch-mode.md
- lib/cli.js
- test/cli.js
> Exit with error if --watch is used in CI

- package.json
> Bump `lodash.isequal`

- docs/recipes/watch-mode.md
- lib/cli.js
- test/cli.js
Improve error message when using watch mode and Ci ([related dsicussion](https://github.com/avajs/ava/pull/1203#discussion_r97516567))
> Improve error message for watch mode in CI

- package.json
> Bump `stack-utils`

- index.js.flow
The work should be the same of #1243
> Flow type definition for snapshot assertion #1245

- package.json
This makes it easier to inspect the code coverage during development.
> Generate HTML coverage reports

- docs/recipes/precompiling-with-webpack.md
Add link to translation "recipe for precompiling source files with webpack" in french
> Docs: Add link to french translation of recipe webpack

- readme.md
According to https://github.com/avajs/ava/pull/1197#issuecomment-289223193
> Remove mention of stage-2 in readme

- lib/sequence.js
> Avoid MaxListenersExceededWarning in Sequence

- docs/recipes/debugging-with-vscode.md
- docs/recipes/isolated-mongodb-integration-tests.md
* Add link to french translation for recipe "Debugging tests with Visual Studio Code"
* Add link to french translation for recipe "Isolated MongoDB integration tests"
> Docs: Add link to french translation (VSCode and MongoDB)

- docs/recipes/vue.md
> Docs: Add link to french translation (Vue.js recipe)

- .travis.yml
- appveyor.yml
- package-lock.json
- test/api.js
- test/fixture/inspect-arg.js
* Commit the lockfile for npm 5
* Test in Node.js 8
* Stop testing in Node.js 7
* Update API test for Node.js 8
> Support npm@5, test with Node.js 8

- package-lock.json
- package.json
> Upgrade concordance

- test/reporters/improper-usage-messages.js
refs: https://github.com/avajs/ava/pull/1457
> add tests for improper-usage-messages

- docs/recipes/endpoint-testing.md
I've wasted blood, sweat, and tears over trying to get tests working, just to realize that I simply had to add `bodyParser` to express.
I hope this will help others.
Thanks for all the fish! (:
> Fixed makeApp() in endpoint testing recipe

- docs/recipes/endpoint-testing-with-mongoose.md
- docs/recipes/isolated-mongodb-integration-tests.md
- readme.md
* Add link to french translation
* Fix 2 bad links discovered during translation
> Docs: Add link to french translation (Endpoint testing with Mongoose)

- index.js.flow
- types/base.d.ts
Follow up to https://github.com/avajs/eslint-plugin-ava/issues/176 and 9100d125f81f53f24779122612244637fc2e6f77 in #1341.
> Add t.title to typedefs

- .travis.yml
- appveyor.yml
- package-lock.json
- package.json
* Update package-lock.json
* Remove flow-bin workaround
* Re-enable locked-deps tests in AppVeyor
> Update to npm@5.4.2

- docs/recipes/typescript.md
> Fix TypeScript recipe typo

- package-lock.json
- package.json
Use https://www.npmjs.com/package/lock-verify to ensure the
package-lock.json is in sync with package.json.
> Verify package-lock when linting

- contributing.md
Update the link to Richard Littauer's guide on amending a commit in an existing Pull Request
> FIX: Broken Link to Update an Exiting PR

- readme.md
> snapshotLocation -> snapshotDir

- docs/support-statement.md
- maintaining.md
- package.json
- readme.md
> Add support statement

- package.json
> Use prepare script

- docs/recipes/vue.md
As someone relatively new to AVA, it wasn't clear to me initially where this json went in the project. It wasn't until I dug through https://github.com/eddyerburgh/vue-test-utils-ava-example/blob/master/package.json that I understood. Having this line would have avoided some confusion.
> Clarify JSON location for Vue recipe 

- docs/recipes/babel.md
- docs/recipes/flow.md
... and fix bad link to babel doc french
> Docs: Add link to french translation (flow)

- docs/recipes/es-modules.md
Add link to es-module in french
> Update links to French docs translations

- docs/recipes/test-setup.md
> Link to French translation of test-setup recipe

- api.js
Babel config is hard to reload. Plugins and presets may be in the require cache. AVA may detect changes and update its cache keys, but because of the require cache the compilation output may not take the changes into account. This ends up polluting the compilation cache.
Change the API implementation so it caches the Babel config. This only impacts watch mode.
> Don't reload Babel config in watch mode

- docs/recipes/passing-arguments-to-your-test-files.md
> Link to French translation of Passing arguments recipe

- docs/recipes/code-coverage.md
nyc is now officially part of Istanbul. They also have a tutorial on how to integrate it with Babel. We should simplify the recipe so it's only about using nyc with AVA. I've left the .gitignore bit, but removed
Coveralls since it's not directly related to AVA.
> Simplify code coverage recipe

- docs/recipes/react.md
Progress #1662
Updated links and babel references to match babel 7. I didn't update any grammar so I'm happy to update the French and Spanish docs if you'd like just let me know.
> Update recipes #3

- docs/recipes/jspm-systemjs.md
> Updating recipes

- docs/recipes/typescript.md
Fixes #1822
I removed the translation links, because it's such a large update. Should I undo this?
TODO:
> Update typescript recipe

- .travis.yml
- appveyor.yml
- package.json
- test/helper/cli.js
- test/integration/assorted.js
- test/integration/compilation.js
- test/integration/stack-traces.js
- test/integration/t-throws.js
> Restore integration tests; drop Node.js 9

- lib/cli.js
- lib/watcher.js
- test/fixture/watcher/custom-extensions/package.json
- test/fixture/watcher/custom-extensions/test.foo
- test/integration/watcher.js
- test/watcher.js
Fixes #1881.
Still need to add an integration test, but this is done otherwise.
> Watcher custom extensions

- lib/fork.js
- lib/worker/fake-tty.js
- test/fixture/tty/color-disabled.js
- test/fixture/tty/color-enabled.js
- test/fixture/tty/get-color-depth-missing.js
- test/fixture/tty/is-not-tty.js
- test/fixture/tty/is-tty.js
- test/helper/simulate-tty.js
- test/integration/tty.js
> Fake TTY support for stderr

- profile.js
> Fix missing `projectDir` in profile.js

- lib/reporters/mini.js
- test/fixture/report/edge-cases/ava-import-no-test-declaration.js
- test/fixture/report/edge-cases/import-and-use-test-member.js
- test/fixture/report/edge-cases/throws.js
- test/helper/report.js
- test/reporters/mini.edgecases.log
- test/reporters/mini.js
- test/reporters/mini.regular.log
- test/reporters/mini.typescript.log
- test/reporters/tap.edgecases.log
- test/reporters/tap.js
- test/reporters/verbose.edgecases.log
- test/reporters/verbose.js
> Better reporting of files without tests

- api.js
- package-lock.json
- package.json
I needed this logic in a couple different places so I turned it into a package with tests and shit
> Replace CI parallelism logic with package

- docs/recipes/babel.md
- lib/babel-pipeline.js
- package-lock.json
- package.json
- readme.md
> Restore Babel cache invalidation

- docs/recipes/puppeteer.md
> Link to French translation of puppeteer recipe

- test/ts-types/throws.ts
Follow-up to https://github.com/avajs/ava/pull/1956.
> Use ts-ignore comment

- index.d.ts
- index.js.flow
I'm assuming this is what you meant and it was just a copy and paste error
> Fix snapshot skip interface

- docs/06-configuration.md
This PR Fixes #1989 . Updated the docs to clarify the usage of CLI options.
> Updated docs to clarify the usage of CLI options

- readme.md
> Fix npm install command in readme

- lib/reporters/improper-usage-messages.js
- test/reporters/mini.regular.log
- test/reporters/verbose.regular.log
> update documentation of error message

- docs/06-configuration.md
fix babel recipe link in configuration doc
> fix: fix babel recipe link

- test/chalk.js
For #161 
I've added  two tests for lib/chalk.js
> Added few tests for lib/chalk.js

- lib/assert.js
> Check whether the code expectation was given

- lib/watcher.js
- test/integration/watcher.js
- test/watcher.js
For #1525 issue
I've added info printing functionality for shortcut commands
> Added info for shortcut commands in watch mode (#1525)

- lib/worker/fake-tty.js
- package-lock.json
- test/fixture/tty/is-tty.js
Implement all tty methods in fake-tty.js
Fixes #2041
> Implement all tty methods in fake-tty.js

- index.d.ts
- index.js.flow
> Add t.assert() to type definitions

- index.d.ts
> Improve the TypeScript definition `ObservableLike` type

- docs/05-command-line.md
- lib/cli.js
> Document timeout units

- .travis.yml
- package.json
> Stop testing Node.js 11, remove from engines entry

- lib/fork.js
- lib/worker/fake-tty-has-colors.js
- lib/worker/fake-tty.js
- test/helper/simulate-tty.js
- test/integration/node-assertions.js
Fix https://github.com/avajs/ava/issues/2170
> Implement `stream.hasColors()` in fake-tty.js

- lib/cli.js
- lib/load-config.js
- test/integration/assorted.js
Fixes #2158
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#2158: Ensure files passed through CLI exist, and are files, before precompiling](https://issuehunt.io/repos/26820798/issues/2158)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>
> Fixes #2158: Ensure files passed through CLI exist, and are files

- lib/reporters/tap.js
- test/reporters/tap.failfast2.log
- test/reporters/tap.regular.log
fixes #2142 
This contains specs modifications for #2178
> Not count hooks as tests

- readme.md
Fixes #2207 
Added Donation link under Links.
> added Donation Link to README.md under Links section

- .travis.yml
While GitHub Actions are in beta, that CI workflow only runs if contributors are also in the beta. Let's run some tests in Travis for the time being.
> Run some tests on Travis still

- docs/support-statement.md
And some other small changes in the support statement.
> Require latest Node.js release whenever we do a major release

- .iron-node.js
- profile.js
I don't think this is still a thing?
> Remove iron-node mentions

- lib/reporters/tap.js
> TAP: Report hook failures as test failures

- docs/recipes/endpoint-testing.md
> Correcting casing in endpoint testing example

- docs/recipes/endpoint-testing-with-mongoose.md
new syntax found here: https://github.com/nodkz/mongodb-memory-server
> Update mongodb-memory-server import in recipe

- lib/watcher.js
- package-lock.json
- package.json
I inlined what both array-union and array-uniq basically do so we don't have to depend on them.
> Remove array-union and array-uniq dependencies

- lib/cli.js
I'd inadvertently disabled color entirely.
> Fix color initialization

- lib/cli.js
- lib/fork.js
- lib/worker/load-chalk.js
- lib/worker/subprocess.js
- test/api.js
- test/assert.js
- test/helper/report.js
- test/test-try-commit.js
- test/try-snapshot.js
This Chalk upgrade is proving more tricky than expected 😉
> Initialize Chalk in worker processes with same level as main process

- docs/03-assertions.md
- index.d.ts
- lib/assert.js
- test/assert.js
- test/fixture/report/regular/traces-in-t-throws.js
- test/reporters/mini.regular.log
- test/reporters/verbose.regular.log
- test/test.js
> Remove legacy .throws() and .throwsAsync() interfaces

- lib/worker/subprocess.js
- package-lock.json
- package.json
> Final tweaks

- package-lock.json
- package.json
Rebuilding the package-lock to get all the latest transitive dependencies.
> Use latest @ava/babel and rebuild package-lock

- docs/recipes/testing-with-selenium-webdriverjs.md
- readme.md
Hi,
This pull request fixes #1023. It adds the recipe for using Selenium WebDriverJs (official JavaScript version) with AVA for testing web applications.
> Add Selenium WebDriverJS recipe

- lib/cli.js
> Fix --update-snapshots

- lib/load-config.js
> Make console & process globals available to ava.config.js files

- lib/api.js
- lib/cli.js
> Disable timeouts in debug mode

- docs/05-command-line.md
- lib/cli.js
> Lowercase CLI argument description asides

- docs/recipes/typescript.md
Previous iteration had configuration that is no longer necessary for version 3.
Closes #2376
> docs(typescript): Updates Typescript Recipe

- eslint-plugin-helper.js
- lib/cli.js
- lib/globs.js
- lib/provider-manager.js
- lib/watcher.js
- lib/worker/subprocess.js
- test/api.js
- test/globs.js
- test/helper/report.js
- test/watcher.js
See https://github.com/avajs/typescript/pull/11.
> Improve integration with TypeScript provider

- lib/beautify-stack.js
- package-lock.json
- package.json
Recognize new @ava/require-precompiled dependency when beautifying stack traces.
> Upgrade @ava/babel

- docs/recipes/vue.md
Fixed `Super expression must either be null or a function`
> Update Vue recipe to use JSDom rather than browser-env

- index.d.ts
- package-lock.json
- package.json
- test/ts-types/tsconfig.json
> Remove @types/node reference

- lib/beautify-stack.js
- package-lock.json
- package.json
- test/helper/report.js
@sindresorhus is publishing too quickly…
> Bump dependencies

- index.d.ts
- lib/assert.js
- test/assert.js
> support undefined as second argument to throws and throwsAsync

- lib/load-config.js
- test/integration/config.js
- test/load-config.js
> Evaluate ava.config.js scripts in current context

- lib/test.js
[Motivation](https://github.com/avajs/ava/pull/2459#discussion_r410686780)
> Remove now unnecessary `finishPromised()` from lib/test.js

- package-lock.json
- package.json
> Upgrade matcher

- lib/line-numbers.js
- xo.config.js
> Fix picomatch dependency

- index.d.ts
- test-d/like.ts
See https://github.com/avajs/ava/issues/2518#issuecomment-651771859
> Fix t.like() selector type

- docs/recipes/debugging-with-vscode.md
> Fix typo in VSCode recipe

- readme.md
remove a dead link, the website is gone.
> remove avacasts.

- lib/reporters/tap.js
> Fix timeout reporting in TAP reporter

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/ci.yml
- package.json
- readme.md
- Update issue template
- Remove badges from readme
- Advertise GitHub Discussions
- Avoid linting for every run in the test matrix
- Update GitHub Actions
> Housekeeping

- docs/recipes/watch-mode.md
According to https://github.com/avajs/ava/discussions/2707#discussioncomment-461257
> Update suggested AVA invocation in watch mode recipe

- lib/scheduler.js
- test-tap/api.js
- Write synchronously and ignore errors
- Change filename
- Fix integration test
> Scheduler follow-up

- entrypoints/eslint-plugin-helper.cjs
- Time out ESLint config resolution after 10 seconds
- Correctly resolve ESLint plugin helper worker path
Fixes #2730.
> ESLint plugin helper fixes

- lib/cli.js
- package-lock.json
- package.json
> Remove `update-notifier` dependency

- lib/fork.js
- lib/worker/base.js
See discussion in https://github.com/nodejs/node/issues/38418
> Attempt to workaround worker thread termination crash

- docs/03-assertions.md
- lib/assert.js
- test-d/throws.ts
- test-tap/assert.js
- types/assertions.d.ts
> Return undefined when throws assertions fail

- lib/load-config.js
- package-lock.json
- package.json
- test-tap/fixture/process-cwd-default.cjs
This reverts commit 1d5d65e016343ff0b1b118d4c085b6e82d244e1b.
> Upgrade pkg-conf

- lib/api.js
This is a regression I introduced in d36806a1d0bb2f19fe274293b326a54eddd32832.
> Fix discarding of timeout trigger

- lib/snapshot-manager.js
> Handle path sources

- docs/03-assertions.md
> Refer to assertion inputs as "actual"

- readme.md
When I did #2954 I didn't spot this one.
> Use ESM import in introductory example

- readme.md
> Add banner to support Ukraine

- docs/03-assertions.md
fix two function name that look like typo.
> Fix function reference in t.try() assertion documentation

- .github/workflows/ci.yml
Run tests against newly released node v20
> Add Node.js 20 to test matrix

- lib/snapshot-manager.js
- package-lock.json
- package.json
I renamed the package from `mem` to `memoize`.
> Update memoize dependency

- readme.md
- Clarify why we've posted the Ukraine war CTA and remove the third-party banner
- Remove Twitter link
- Thread isolation, not process (at least by default)
- Fix link
- Remove outdated comparison with mocha/tape/tap
> Tweak README

- docs/01-writing-tests.md
Add link to detail how you can fall back running in separate process.
> Link to CLI options to clarify how to run tests in separate processes

- package.json
As recommended by 'npm pkg fix'.
> Adjust repository reference in package.json
