lib/test.js

`EventEmmitter` is not used in `Test` class and seems like won't be used in future (nor exposed in readme).

remove EventEmitter from Test

---

lib/test.js
test/test.js

Having a test with a `plan` which throws an unexpected error like so:
```javascript
var test = require('ava');
test(function unexpected(t) {
t.plan(1);
var o = {};
o();
});
```
Will at the moment only report an error about assert count not matching planned count, even though an `assertError` already have been set. This addresses that by not overwriting an existing assert error, which gives the correct error message:
```
TypeError: o is not a function
```
What do you think?

Easier debugging when not overwriting already existing assertErrors

---

cli.js

This PR fixes a bug caused by #47.
When there is only one test file, AVA does not report a number of passed/failed tests.
The reason is the `sum()` function, that is used to sum up all passed/failed counters from all tests:
```js
function sum(arr, key) {
return arr.reduce(function (a, b) {
return a[key] + b[key];
});
}
```
When `arr` has only one item, it simply returns it, without calculating a sum, which leads to a reported bug.
Fix is very simple:
```js
function sum(arr, key) {
var result = 0;
arr.forEach(function (item) {
result += item[key];
});
return result;
}
```

Fix passed/failed counters

---

lib/test.js
test/test.js

Fixes #63, related to #15.
Before test `.run()`, timer with maximum possible value is started to keep the process alive. When the test is finished, `clearTimeout()` removes the timeout.
Now, the following tests won't just produce empty output:
```js
test('empty test', function (t) {
});
test('no assertions', function (t) {
t.plan(1);
});
```

Wait for pending tests

---

cli.js
lib/babel.js
lib/fork.js
package.json
test/fixture/async-await.js
test/fixture/generators.js
test/test.js

Fixes #53 
Uses `figures.pointerSmall` to replace `/` and as a separator between prefix and test title.

Prefix test title with test location

---

index.js
lib/runner.js
readme.md
test/test.js

This PR adds `beforeEach()` and `afterEach()` methods to Ava.
These functions allow to add hooks that are executed before & after each test.
`beforeEach` and `afterEach` hooks execute serially, just like `before` and `after`.
There is one difference though, if `beforeEach` hook fails, tests don't stop (unlike `before`).
So, let's discuss this!

Add beforeEach/afterEach hooks

---

lib/assert.js
lib/test.js
test/test.js

This PR introduces the ability to handle promises in `t.throws()` and `t.doesNotThrow()` methods.
Refs #73.
Changes:
- In `lib/test.js` check, if assertion function returns promise and act accordingly
- Improve `t.throws()` and `t.doesNotThrow()` methods to handle promises
- Change test names related to functions above to be more clear
Let me know what you think ;)

Handle promises in throws() and doesNotThrow()

---

lib/test.js
test/test.js

This PR implements support to `t.plan()` + promises cocktail.
Fixes #75.
Example:
```js
test(function (t) {
t.plan(1);
var promise = Promise.resolve();
setTimeout(function () {
t.pass();
// now test is finished
}, 200);
return promise;
});
```

Add support to t.plan() + promises

---

cli.js
index.js
lib/fork.js
readme.md
test/fixture/fail-fast.js
test/test.js

This PR adds `--fail-fast` option to exit after the first test failure.
Fixes #48.
Changes:
- add `--fail-fast` option to `--help` output
- add fail-fast mode
- add tests

Add fail-fast mode

---

lib/logger.js
lib/runner.js
test/test.js

This PR fixes #89.
Now AVA ensures that hooks run only around tests. Previously, hooks were running also around `before` and `after`, which is not quite good.

Run hooks only around tests

---

lib/assert.js
test/test.js

This PR fixes #86 and fixes #85.
It improves `t.throws()`, so that it avoids false-positives results and supports regex, just like native `throws()`.

Fix t.throws() behavior to avoid false-positives and regex suport

---

index.js
lib/fork.js

This PR closes #97.
After this PR, `node test.js` is not possible. Only `ava test.js`.

Support running the test file only via CLI

---

cli.js
lib/runner.js
readme.md
test/fixture/serial.js
test/test.js

This PR closes #31.
It adds `--serial` option, which forces AVA to run all tests serially by default.

Add serial mode

---

lib/babel.js
test/fixture/babel-hook-imported.js
test/fixture/babel-hook.js
test/test.js

since we're only using this once per file now
http://babeljs.io/docs/usage/options/#options

use the test file path in the Babel `only` prop instead of a pattern

---

lib/runner.js
lib/test.js
test/test.js

This PR resolves the following use case:
```js
test.beforeEach(t => {
this.data = generateUniqueData();
});
test('some data', t => {
// use this.data
});
```
With this PR, context (`this` object) is shared between test and **beforeEach**/**afterEach** hooks (not **before** or **after**).

Shared context between tests and beforeEach/afterEach hooks

---

lib/runner.js
lib/test.js
readme.md
test/test.js

re https://github.com/sindresorhus/ava/pull/106#issuecomment-150966370

improve context sharing for beforeEach/afterEach

---

lib/test.js

Finally found the solution for #123 
By returning the promise, it's possible to check the throwed error like this which succesfully waits untill the promise is resolved/rejected.
```js
test(async t => {
await t.throws(throws(), /hello world/);
function throws() {
return new Promise(function (resolve, reject) {
setTimeout(function () {
reject(new Error('hello world'));
}, 2000);
});
}
});
```

Throws returns the promise

---

cli.js
lib/fork.js
test/fixture/long-running.js
test/fork.js

Killing the parent process skips execution of `end` listeners
on remaining forked child processes.
This interferes with `nyc` if processes are kept running after
test completion.
Refrence: https://github.com/bcoe/nyc/issues/52

Forcibly kill every forked subprocess.

---

cli.js
lib/fork.js
test/fork.js

@jamestalmage here's the refactored solution to the issue you mentioned - https://github.com/sindresorhus/ava/pull/134/files#diff-a48173105195b7a6481a3ad85b45144eR27.
The "trick" is to kill the forked process after the test results are received and not let `cli.js` handle this mess.

Kill forked processes after tests are done

---

lib/fork.js
test/fixture/process-cwd.js
test/test.js

Improves #134.
// @jamestalmage

Wait for fork to exit and then return results

---

lib/babel.js

Fix #129
Fix error that babel-plugin-espower resolves a different Babel version.
```
C:\Users\Frontend\AppData\Roaming\nvm\v0.12.5\node_modules\ava\node_modules\babel-core\lib\transformation\plugin.js:121
throw new TypeError(messages.get("pluginNotFile", this.key));
^
TypeError: Plugin "babel-plugin-espower" is resolving to a different Babel version than what is performing the transform
ation.
at Plugin.buildPass (C:\Users\Frontend\AppData\Roaming\nvm\v0.12.5\node_modules\ava\node_modules\babel-core\lib\tran
sformation\plugin.js:121:13)
at PluginManager.add (D:\Workflow\sandbox\aa\node_modules\babel-core\lib\transformation\file\plugin-manager.js:216:5
5)
at File.buildTransformers (D:\Workflow\sandbox\aa\node_modules\babel-core\lib\transformation\file\index.js:237:21)
at new File …
```

Use local babel in babel-plugin-espower

---

lib/babel.js
package.json

Drawback - now you can require any module from `ava/node_module` in tests.
Closes #144

Add ava modules to test module paths

---

lib/fork.js

Related - https://github.com/nodejs/node-v0.x-archive/issues/8667
Closes #154.

Check for SIGTERM exit code

---

lib/test.js
test/test.js

test() should throw if no callback is provided. Fixes #172

---

readme.md

Just some glaring issues in the README. :+1:

Minor readme fixes

---

index.js
lib/runner.js
lib/test.js
test/fixture/hooks-failing.js
test/fixture/hooks-passing.js
test/test.js

This PR fixes #105.
From now on, AVA displays only hooks that failed. This results to a dramatically cleaner output:
**Before**:
**After**:

Display only failed hooks

---

index.js

This PR fixes #179.
Here's the output:

Fail when tests executed without cli

---

cli.js
index.js
lib/logger.js
lib/runner.js
test/test.js

This PR lays groundwork for #132 and #192 by allowing to easily send & receive custom test properties.

Event data improvements

---

index.js
lib/logger.js
lib/runner.js
test/test.js

This PR fixes #192.
It allows you to use `test.skip()` to skip the whole test. The output for skipped tests is like that:

Add test.skip()

---

lib/fork.js
test/test.js

It is generally recommended to reject Promises with an error.
This becomes especially true with the move to `async/await`,
as `Promise.reject(1)` essentially becomes `throw 1` in that context.
Not doing so was causing a weird bug on Node 0.10.
Ref: https://travis-ci.org/sindresorhus/ava/jobs/90709377#L779

fork.js: Reject child-process completion promise with an error.

---

lib/logger.js
test/fixture/one-pass-one-fail.js
test/test.js

log.errors() cycles through all the results from a file (passing and failing)
and prints out a summary of the failing tests and the assertion errors.
It was misidentfying all results as errors, and then throwing
when result.error turned out to be an empty object ({}).
I think the result object can be improved such that
result.error === false when there were no errors.
But that is for another PR.

regression: logger throws on files with both passing and failing tests.

---

lib/runner.js

The wrapper is not necessary, even for primitives.
// @sindresorhus

simplify context sharing between beforeEach and test

---

cli.js
index.js
lib/babel.js
lib/fork.js
lib/runner.js
lib/send.js
test/fixture/long-running.js
test/fork.js
test/test.js

This is a clean up kind of PR, not refactoring.

Clean up forking and messages

---

lib/runner.js

Small cleanup of `lib/runner.js`

Clean up runner

---

lib/babel.js
package.json
test/cli.js
test/fixture/uncaught-exception.js

Fixes #223, #250 
This adds basic source map support. Since transpilation of dependencies
is not merged yet, the `sourceMapCache` object and lookup is a little
premature (since we will only ever have one file that we can apply
apply source maps to).

Add source map support. Fixes: #223, #250

---

lib/test.js
test/hooks.js

IMO, since context is not shared in `before` and `after` hooks.
It should be an error to access it in either scenario.
(cherry picked from commit f298d72 on #243)

context should not exist on before/after tests.

---

.travis.yml
package.json

For PR's `process.env.COVERALLS_REPO_TOKEN` does not exist, so `tap`
will **not** automatically send data to coveralls. Hence our existing script:
`npm run coveralls`. Unfortuneately that seems to create problems
when merged onto master. In that case `tap` **will**
automatically push our coverage data, and the follow up script seems to fail.
To fix all this, I check the environment variable in .travis.yaml, and
manually push the coverage data if the environment variable does not exist.
Example Failing Build: 
https://travis-ci.org/sindresorhus/ava/jobs/92855751

Fix failing coveralls script.

---

lib/runner.js
lib/test.js
package.json
readme.md
test/fixture/circular-reference-on-assertion.js
test/fixture/es2015.js
test/fixture/fail-fast.js
test/fixture/hooks-failing.js
test/fixture/hooks-passing.js
test/fixture/long-running.js
test/fixture/loud-rejection.js
test/fixture/one-pass-one-fail.js
test/fixture/power-assert.js
test/fixture/process-cwd.js
test/fixture/serial.js
test/hooks.js
test/observable.js
test/promise.js
test/runner.js
test/test.js

Breaking: `t.end` requires `test.async`, and `t.plan` will not auto end tests. Fixes #244.

---

cli.js
lib/babel.js
package.json

I want to start focusing on getting our require times down,
both in the main thread and forked tests.
This adds `time-require` support directly to the CLI to assist in that.
This is especially important for forked test processes, where I currently
have to manually add a line of code each time I want to test an optimization.
I don't think this should be a publicly documented move. I think we want
the freedom to remove this once we are happy with performance.
I have placed comments above all `time-require` references, indicating
it is for internal use only. Users have been given fair warning against
relying on its inclusion long term.
Usage:
```sh
$ ./cli.js test/fixture/es2015.js --time-require --sorted
```
`--sorted` is optional. It sorts the requires from most expensive to least. The …

Integrate time-require into the CLI.

---

cli.js
lib/fork.js

This passes terminal width information to, and enables ansi-color
support in, the forked process. It makes the output of `time-require`
much prettier when used in a fork.

Pipe forked IO streams instead of forwarding `data` events.

---

cli.js
package.json
readme.md

This hunts for AVA in the locally installed project, and runs that
CLI instead of the globally installed one.
Fixes #157.

Prefer the locally installed version of AVA.

---

test/cli.js

Found the source of recent AppVeyor flakiness.
"someone" removed my fix. :smile:

Put back AVA_APPVEYOR environment variable when running tests.

---

cli.js

When there's no local `ava` installed, global CLI crashes:

Don't crash when there's no local AVA

---

lib/test.js

I considered the delegates module, but that still requires exposing the Test
object itself as a member of `api`, and does not bind `this` for the exposed
functions.
Fixes #252.

Hide test internals. Fixes #252.

---

api.js

c424ceb3d introduced a regression in how we format uncaughtExceptions.
The wrong value was being passed to the logger.

Fix regression in uncaughtException formatting.

---

index.js
lib/babel.js
lib/fork.js

There are two possible errors that can result in no test data being
received.
1. The user never imports `ava` in their test file.
2. The user has not written any tests in the file yet.
We treat both as errors, but were handling them differently.
Most problematic, one caused the promise to resolve, the other
caused the promise to reject.

Unify how files with no tests are reported.

---

index.js
lib/runner.js
test/runner.js

Fix regression introduced in #243. Skipped tests were ignored and not displayed in the output. This PR brings back skipped tests:

Display skipped tests

---

lib/test.js
test/fixture/destructuring-public-api.js
test/fork.js

There were two problems with using destructuring on the `t` parameter passed to tests:
1. `t.end` is enumerable, but throws when accessed. 
This created problems when destructuring using rest params `{ok, ...t}`. 
The solution: `t.end` is enumerable only in "callback mode".
2. `t._capt`, `t._expr` are not enumerable, 
and therefore not exposed as a member of the `...t` rest param.
The only solution was to make them enumerable. 
Not ideal, but better than the confusing error that previously occurred.

allow destructuring of `t` parameter.

---

lib/assert.js
package.json
test/assert.js

Introduces an additional dependency: `deeper`.
Fixes #298.
Alternate to #300.

Allow deepEqual comparison of values with circular references. Fixes #298.

---

api.js
index.js
lib/babel.js
lib/fork.js
lib/runner.js
package.json

This PR attempts to fix #318 .
Initially, the JSON string is converted back into `process.argv` values in lib/babel.js. I'm happy to go further and actually try to eliminate `--fail-fast` and `--serial` altogether in the child process, but I figured it was worth sharing what I had so far.

process is forked with a single JSON argument

---

api.js
cli.js
lib/babel.js
package.json
readme.md
test/api.js
test/fixture/install-global.js
test/fixture/validate-installed-global.js

I figured I'd have an attempt at being able to pass the `--require` through to the Node executable used for the child process (#229).
My test project uses `import` and `export`, so doesn't execute in Node v5 without babel/register. I can manually confirm using `npm link` that the changes I have so far function as expected.
Besides general comments (very much appreciated), I'm a little bit at a loss as where to start with the tests. Do I need to confirm (with tests) that the `ava --require moduleId` works? Or is it sufficient to use mocks and confirm that arguments are being passed through as expected?

Node.js-style --require CLI argument

---

lib/assert.js
test/api.js

This helps out with #315 by adding a default message to `x.fail()` so that the failing message is always helpful.
If there's a better message to use, let me know! It's a quick change.

Change `false fail false` message

---

lib/babel.js
readme.md

Instead depend on npm to dedupe. This is better as we will no longer fail if the user has Babel 6 and we Babel 5, and npm just won't dedupe. Same situation in the future when we're on Babel 6, but the user is still on Babel 5.

don't use local Babel directly

---

test/api.js
test/cli.js

This helps out with https://github.com/sindresorhus/ava/issues/256 by converting the regex `t.true()` tests into `t.match()`.
Let me know if I missed any!

Use `tap.match` in unit tests

---

api.js

Hi All,
This is a simple PR, it just fixes a warning from bluebird (about deferreds).
Enjoy!

Fix bluebird warnings

---

test/cli.js

This helps with https://github.com/sindresorhus/ava/issues/161 by adding one test to the CLI tests that makes sure failed tests are logged.
I'm actually not sure if this test is needed—I just saw that it was an "uncovered" line on Coveralls and indeed the coverage went up after writing it.

Add CLI test for logging failed tests

---

lib/babel.js

Also seems to make Babel 5 support "just work".

Require babel plugins directly. Fixes #350.

---

contributing.md

As requested: https://github.com/sindresorhus/ava/pull/346#issuecomment-166789457

contributing.md - seek early feedback

---

api.js
readme.md
test/api.js
test/fixture/ignored-dirs/fixtures/test.js
test/fixture/ignored-dirs/helpers/test.js

This fixes https://github.com/sindresorhus/ava/issues/355 by adding the required code to ignore files in directories named `fixtures` and/or `helpers` as well as documentation and tests.

Ignore files in fixtures and helpers directories

---

cli.js
lib/beautify-stack.js
lib/reporters/mini.js
lib/reporters/verbose.js
package.json
readme.md
test/reporters/mini.js
test/reporters/verbose.js

This PR fixes #18.
Replacing default reporter with a mini one:
It also adds `--verbose` option, which enables old full-blown output.

Add mini reporter

---

api.js
lib/test.js
test/promise.js

This PR fixes #271. Now AVA shows full stack trace for non-assertion errors. Before, it wrapped them in `assert.AssertionError`, which swallowed the original stack.

Show full stack trace for non-assert errors

---

api.js
cli.js
lib/ava-error.js
lib/fork.js

This PR fixes #368.
Now we use `AvaError` for internal errors, that don't need a stack trace.

Use AvaError for internal errors

---

lib/reporters/mini.js
test/reporters/mini.js

This PR fixes #372.
Mini reporter (default one) was not displaying power-assert output. Now it does (along with a stack trace):

Display power-assert output in mini reporter

---

api.js
package.json
test/api.js
test/fixture/subdir/failing-subdir.js
test/fixture/subdir/in-a-subdir.js
test/fixture/subdir/nested/nested.js

OK @sindresorhus, This is half of #373, and half of the fixes #370. I think the git history is pretty clean, but let me know if there's anything I should fix.
Before:
After:
Files:

Better test prefixes

---

api.js
cli.js
readme.md
test/api.js
test/fixture/subdir/failing-subdir.js
test/fixture/subdir/in-a-subdir.js
test/fixture/subdir/nested/nested.js

This changes the current behavior when a user specifies a directory in a glob pattern, i.e.:
Consider:
```
$ ava tests
```
Currently, this would only include all `.js` files in the `tests` directory, but not subdirectories. 
With this change, all `.js` files in the `tests` directory and all sub directories (infinitely deep) will be included.
Fixes #249.

Deeply recurse directories

---

package.json

This uses `nyc` directly instead of via `tap`. There is currently some semver brokeness happening due to a major version bump in `nyc` making it's way into a minor version bump for `tap`. I think the easiest solution is just to avoid the problem altogether by turning off `tap`s coverage option and using `nyc` directly.
Reference:
https://github.com/isaacs/node-tap/pull/197
---
This also switches us to the `classic` reporter. Historically were using `dots` reporter with `tape`, but that provided poor diagnostic information on failures. The `classic` reporter does a much better job of providing all the information we need when a test fails.

Improve test scripts

---

lib/fork.js
package.json
test/cli.js
test/fork.js

Fixes #339.
To get the correct file and line number from `SyntexError`s, we need to give up control of how they are logged to console (see #308 for a full discussion on why this is true).
The unfortunate side effect was that tests exercising our syntax errors
I was not sure this was worth it (it is a lot of code two fix the output from just two tests), but then I [stumbled on this](https://github.com/sindresorhus/ava/commit/5e6327de2dcdc7a63d7d53f505673dbfd7973393). There seem to be situations where [a bad plan count, will not fail the tap test suite](https://github.com/isaacs/node-tap/issues/198). Now I think this is probably worth the effort.

Hide annoying error print outs.

---

lib/test.js
test/promise.js

Fixes #386.
Previously, AVA expected `Error`s in rejected promises and did not support other types of rejected values. This resulted in a wrong output, marking failed tests as passed.
Now, if promise rejected with non-`Error`, we wrap it into `assert.AssertionError` to ensure promises always reject with `Error`s.

Support promises rejected with non-Errors

---

lib/test.js
test/test.js

This fixes that regression, and extends the promise returning behavior to all assertions.
This would be useful in `async` test functions to bail on the remaining tests if some precondition fails. Simply `await` the assertion.
See: https://github.com/sindresorhus/delay/pull/10

Regression: Assertions should return promises.

---

lib/test-worker.js

We currently only utilize long stack traces in the main thread, not the test threads. This rectifies that.
If we decide to drop Bluebird in forked processes (See #393), this is moot. But if we decide to keep bluebird around, we might as well enable this.

Use long stack traces in forks.

---

test/fixture/babelrc/.babelrc
test/fixture/babelrc/package.json
test/fixture/babelrc/test.js
test/fork.js

If a `.babelrc` file is present, it is being read, and the settings merged with the ones we specify for tests. We don't want that.
Reference:
http://babeljs.io/docs/usage/options/

Stop reading `.babelrc` files.

---

lib/beautify-stack.js
package.json
test/reporters/mini.js
test/reporters/verbose.js

I have extracted `node-tap`s stack cleaning algorithm into it's own module, [`tapjs/stack-utils`](https://github.com/tapjs/stack-utils).
It creates much nicer stack traces than `beautify-stack.js` does. There is a bit of work left to do in the `stack-utils` module, but once these are done, this should be mergeable:
Screenshots below.

Use stack-utils for nicer stack traces.

---

lib/beautify-stack.js

Add babel-runtime and core-js to list of internals. Fixes #429

---

package.json

Skipping `observable-to-promise` for this release because of https://github.com/sindresorhus/observable-to-promise/issues/2
`babel-plugin-transform-regenerator` intentionally held back due to regression in babel (9cf22c3).

Bump dependencies for release

---

lib/assert.js
lib/test.js
package.json

Observable `0.2.0`/`0.3.0` introduced some breaking changes. Namely, it now throws if passed a non-observable.
Reference: https://github.com/sindresorhus/observable-to-promise/issues/2

bump observable-to-promise

---

package.json

This reverts commit 08c3285c3897dde404d698e5f5038edc3f786ca7.
The issue in transform-regenerator has been fixed as of `6.4.4`

Revert "lock `babel-plugin-transform-regenerator` dependency to fix #425"

---

lib/enhance-assert.js
lib/runner.js
lib/test.js
package.json
test/fork.js
test/test.js

Using the [emoji-aware test-per-character branch](https://github.com/beaugunderson/emoji-aware/commit/e2c3a824ec6e28c2e86e9191fd7123cea8ac1e00) as a benchmark, and running `time ava`:
master:
```
4363 passed
ava  22.61s user 0.54s system 109% cpu 21.093 total
```
this branch (only the `Runner` commits):
```
4363 passed
ava  7.30s user 0.51s system 139% cpu 5.597 total
```
this branch (all the commits):
```
4363 passed
ava  6.32s user 0.46s system 145% cpu 4.675 total
```
--- 
updated benchmark (with empower-core performance tweaks):
```
ava --verbose  5.05s user 0.32s system 138% cpu 3.872 total
```

Performance Improvements for files with thousands of tests

---

code-of-conduct.md
docs/recipes/code-coverage.md
docs/recipes/endpoint-testing.md

* code of conduct (Spanish & French)
* recipes
* code coverage (Spanish & French)
* endpoint testing (Spanish & French)

Add links translations for new docs

---

lib/reporters/tap.js
test/reporters/tap.js

This fixes #423 by only outputting the skipped test count in the TAP reporter if there are skipped tests. If there are none, it does not output anything. It also adds a test for this.
[tape](https://github.com/substack/tape/blob/master/lib/results.js#L132) does this and so does [tap](https://github.com/tapjs/node-tap/blob/master/lib/test.js#L882) (thanks to @therealklanni for the line reference for tap!).

Fix undefined skip count

---

api.js
lib/ava-error.js
lib/hook.js
lib/logger.js
lib/runner.js
lib/test.js
test/observable.js
test/promise.js
test/runner.js
test/test.js

To be forward compatible with ES2015 classes.

Consistently require `new` for classes

---

lib/assert.js
lib/enhance-assert.js
readme.md
test/assert.js

Reimplementation of `.regexTest()`, with arguments flipped. The new order aligns with that of the other assertions available on the test context. 
Ref issue; #142

add `.regex()` assertion method

---

lib/test.js

Every call to `t.plan` generates a stack trace. Apparently those stack traces are expensive. This speeds things up by shortening the stack trace.
I am not sure we need more than a depth of 1.
benchmark:
```js
import test from 'ava';
for (var i = 0; i < 10000; i++) {
test(`test${i}`, t => {
t.plan(1);
t.pass();
});
}
```
master:
```
node cli.js test/lots-of-plans.js --verbose  6.16s user 0.58s system 119% cpu 5.647 total
```
depth 1 (current value in this PR):
```
node cli.js test/lots-of-plans.js --verbose  2.43s user 0.48s system 142% cpu 2.044 total
```
depth of 2:
```
node cli.js test/lots-of-plans.js --verbose  2.66s user 0.42s system 128% cpu 2.392 total
```
depth of 3: 
```
node cli.js test/lots-of-plans.js --verbose  3.04s user 0.49s system 133% cpu 2.648 total
```
depth of 4:
``` …
```

Shorten the plan stack.

---

maintaining.md

I added these to the `maintaining.md` so they don't clutter the top of the Readme.
Handles the first step of the Release process at a glance.

Add david-dm.org badges in `maintaining.md`.

---

lib/reporters/mini.js
test/reporters/mini.js

This fixe #479 by adding a `\n` to the output of the mini reporter and updating the current tests so they pass.

Add empty line before output to mini reporter

---

package.json

This tiny PR fixes #509 and #459 when `beautifyStack` returns `null`.

fix beautify stack split error - fixes #509

---

test/cli.js

Removed the warning we are getting when running npm test for test/cli.js.
The warning was:
86:42 warning Expected error to be handled  handle-callback-err

Removed warning for handle-callback-err

---

profile.js

This will automatically start the DevTools profiler when running `profile.js`

auto start the CPU profiler

---

package.json
test/cli.js
test/fixture/watcher/test.js

The watcher tests are fully stubbed. This test verifies it actually works from the CLI.
Fixes #537.

Test watcher from the CLI

---

index.js

Fix test worker crash

---

api.js
index.js
lib/test.js
test/api.js
test/fixture/error-without-message.js
test/hooks.js
test/promise.js
test/test.js

The child processes determine whether the test had an error based on its `error` property not being `undefined`. However they then change this property to an empty object if there was no error.
The API determines whether a test had an error based on its (empty) error object having a `message` property. If a test did not have an error, its `error` property is set to `null`. This prevents errors without messages from being reported correctly.
Instead set `error` to `null` in the child processes and rely on that in the API.
I've added a test to validate errors without messages get reported.
Fixes #553.
Note that I did not check what happens when non-errors are thrown. Either the API code was a guard for that, or it's already handled elsewhere, or it's just really bad practice.

Consistent error determination

---

lib/reporters/mini.js
test/cli.js
test/reporters/mini.js

Fixes #422. Removed the `AssertionError: ...` line of output.

Removed redundant line from assertion error output in mini reporter

---

lib/sequence.js

Previously, Sequence was checking for Promise-type result every time, to detect when a Promise needs to be returned from .run() method, which created a deep Promise chain. This behavior resulted in a big perf loss when AVA was used in big test suites.
After this PR, when Sequence finds Promise-type result it uses Promise.each on all the remaining tests, which should fix the issue with current implementation.
Follow up PR from #495.

Optimize Sequence by using Promise.each

---

api.js
cli.js
lib/test-worker.js
lib/watcher.js
package.json
test/api.js
test/fixture/with-dependencies/no-tests.js
test/fixture/with-dependencies/require-custom.js
test/fixture/with-dependencies/test-failure.js
test/fixture/with-dependencies/test-uncaught-exception.js
test/fixture/with-dependencies/test.js
test/watcher.js

Fixes #115, building on top of the `--watch` implementation.
Test workers keep track of test dependencies for all registered file extensions. These are sent back to the Api as part of the 'teardown' event, ensuring they're captured irrespective of whether tests passed.
The watcher rejects any dependencies that are not source files, matching how Chokidar watches for source file modifications. It maintains a list of source dependencies for each test file.
The watcher will find the test files that depend on modified source files and rerun those (along with any other modified test files). If any modified source files cannot be mapped to test files all tests are rerun. This is necessary because only `require()` dependencies are tracked, not file access.
Run `DEBUG=ava:watcher $(npm bin)/ava …

Only run tests for changed sources

---

index.d.ts

The `context` fix wasn't entirely correct. It was possible to set the `context` in the `before` and `after` tests as well. So had to add some extra things in order for this to work.
// @ivogabe

[t.ds] do not provide context in before and after hooks

---

api.js

Remove declaration and usage for unnecessary `counted` variable in ava/api.js.
This should resolve issue #584

Remove unnecessary `counted` variable in api.js

---

lib/assert.js
readme.md
test/assert.js

If a `throws` assertion passes, we should return the reason for said pass. That entails; 
* A thrown Error.
* A Promise rejection.
* An Observable error. 
Loosely based on the description of #493. I consider it to be loosely based on it, because of the following differences (in the Promised-land): 
```js
// Desired
test(t => {
const expected = new Error('foo');
const actual = t.throws(() => Promise.reject(expected));
t.is(expected, actual); // true
})
// Implemented
test(t => {
const expected = new Error('foo');
const actual = t.throws(() => Promise.reject(expected));
t.is(expected, actual.reason); //true 
})
```
--- 
I hijacked the `result.reason` property because I wasn't fully comfortable in excluding the base `result` properties out of a successful `throws` assertion, which was …

Return thrown error/rejected promise from t.throws

---

api.js
index.js
lib/fork.js
lib/runner.js
test/api.js
test/fixture/exclusive-nonexclusive.js
test/fixture/exclusive.js
test/fork.js
test/hooks.js
test/runner.js

My suggested solution for #549. Needs unit tests, of course.

Support .only for all files

---

.travis.yml
package.json
test/cli.js

Fixes #590. Depends on <https://github.com/sindresorhus/get-stream/pull/6>. Hopefully fixes #498 as well.

Fix watcher test with Node 0.10

---

cli.js
package.json

New XO seems capable of linting `cli.js`.

no longer ignore cli.js when linting

---

test/api.js

This test has failed twice now, see <https://travis-ci.org/sindresorhus/ava/jobs/113902915>. I can't reproduce the error locally, perhaps there is an error that's being swallowed.
Return the promise so tap can report any errors and isn't somehow tempted to end the test early.

try to fix flaky api test

---

api.js
lib/runner.js
test/api.js
test/fixture/match-no-match.js
test/fixture/pkg-conf/precedence/c.js

First commit does some refactoring and fixes a rare race condition where tests are run prematurely.
Second commit implements my suggestions from #606.

Don't run tests if --match has no matches

---

cli.js
docs/recipes/watch-mode.md
lib/watcher.js
readme.md
test/watcher.js

Document watch mode. Fixes #532.
Contains a squashed #597, so just check the last commit. Will rebase once #597 has landed.

Document watch mode

---

lib/reporters/mini.js
test/reporters/mini.js

too much green when the result count is also in green
and with `todo` and `skip` tests it doesn't matter as they're shown too fast anyways

remove color from test title in mini reporter

---

api.js
test/api.js
test/fixture/syntax-error.js

Fixes #622.
Catch exceptions when initially running files. Don't run any tests, just report the exception.
Move test teardown into a callback for the run promise so it can be used when `--match` is used but there are no matches, and when exceptions occur while initially running files.
Teardown causes the test promise to reject, which leads to an attempt to run the tests. Add a guard to prevent this.

Don't crash watch mode when tests files fail to transpile

---

api.js
lib/watcher.js
test/api.js
test/watcher.js

Fixes #593.
The watcher keeps track of exclusive tests. If all test files that contained exclusive tests need to be rerun it runs them without forcing exclusive mode. This means the exclusivity is determined by the tests themselves.
If a test file, containing exclusive tests, is not one of the files being rerun, it forces exclusive mode. This ensures only exclusive tests are run in the changed files, making .only sticky.
If all test files that contained exclusive tests are removed, sticky mode is disabled. The same happens if there are no more exclusive tests after a run.
A second argument can be passed to Api#run(). If true the tests will be run in exclusive mode, regardless of whether exclusive tests are detected. The Api now remits the 'stats' event from the forks.

Make .only sticky in watch mode

---

readme.md

This PR fixes a small typo in `readme.md`.

fix(readme): fix typo

---

readme.md

Two parentheses instead of one.

Docs : fix typo readme

---

api.js
lib/fork.js

Fixes CI failures like <https://travis-ci.org/sindresorhus/ava/jobs/115088398>. See <https://github.com/novemberborn/_ava-tap-crash> for background.

Fix run crashes

---

index.d.ts

```
$ $(npm bin)/tsc --noImplicitAny
node_modules/ava/index.d.ts(132,2): error TS7010: 'throws', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/ava/index.d.ts(136,2): error TS7010: 'notThrows', which lacks return-type annotation, implicitly has an 'any' return type.
```

fix index.d.ts for noImplicitAny option

---

lib/reporters/mini.js
test/reporters/mini.js

This PR fixes #628.
Mini reporter now shows skipped/todo tests only at the final output with all the results.

Don't log skip/todo tests in mini reporter

---

cli.js
test/cli.js
test/fixture/invalid-babel-config/package.json

This PR fixes #623.
If `babel` config value is invalid, AVA now shows an error:

Show error if babel config value is invalid

---

readme.md

Hello everybody :smiley:!
This is really a minimal fix but I noticed, while working on https://github.com/babel/babel.github.io/pull/758, that in the `readme.md`, the AVA's default Babel configuration is incorrect: it includes the `"stage-0"` preset in place of the `"stage-2"` preset stated just few lines above and also [here](https://github.com/sindresorhus/ava/blob/6d5f3225cc712f10e7a0a8a9c6e40d574fd4b251/package.json#L85).
Again, it's just a super minor fix, but it can lead to possible problems if you cut-and-paste the default configuration.
Thanks :smile:!

fix default AVA's Babel configuration in readme.md

---

lib/test.js
test/test.js

PR #576 changed the `t.throws()` assertion to return the thrown error, or if asynchronous a promise for the rejection reason. Unfortunately this only worked for asynchronous errors.
The tests cover the changes in `lib/assert.js` but `t.throws()` is an *enhanced* assertion. This commit ensures any values returned from `lib/assert.js` assertions are indeed returned by the corresponding `t.` assertions.

Ensure t.throws() returns the error

---

lib/caching-precompiler.js
lib/test-worker.js
package.json
test/caching-precompiler.js

I think messing with the module path is a bad idea, it seems like an easy way to create hard to reproduce bugs.
Also, if a user installs their own version of `babel-runtime`, we have no guarantee it is compatible with the one needed by our tests. By rewriting to absolute paths, we can completely bypass whatever version the user installs locally.
This PR adds a babel-plugin which rewrites all `babel-runtime` requires to absolute paths.

Rewrite all `require('babel-runtime/**)` statements to absolute paths

---

docs/recipes/watch-mode.md
lib/watcher.js
package.json
test/watcher.js

Rerun tests using "r" key in watch mode

---

lib/caching-precompiler.js
lib/test-worker.js
test/caching-precompiler.js

In <https://github.com/kentcdodds/react-ava-workshop/pull/5> nyc is instrumenting the test files. Due to how our caching precompiler works nyc doesn't realize it's instrumenting the transpiled code. It can't find a source map for the transpiled code causing it to crash when generating coverage reports.
Generating coverage reports for test files shouldn't be necessary (and nyc excludes them by default), but it's not something that should crash either.
This PR adds a source map file comment to the cached code. The path is relative to that of the original file, allowing nyc to resolve the source map.
It also changes the source map file extension to the more conventional `.js.map`.
I think this is a better fix than #655 since we don't have to include the source map in an inline comment. The …

Ensure source map can be resolved from cached code

---

lib/test.js
test/test.js

Fixes #102
The assertion error already had `expected` and `actual` properties, but only the tap reporter displays those. Instead of modifying existing reporters to handle the special case of planned assertions, I took the easy way out and just dynamically generated the error message.

Print the planned and actual assertion count when incorrect.

---

contributing.md

See [this](https://github.com/sindresorhus/ava/pull/663) PR which inspired this addition to `contributing.md` :-)

add note about AVA mantra in contributing guidelines

---

lib/fork.js
test/fixture/immediate-3-exit.js
test/fork.js

As discovered in #604 child processes can be killed by outside parties. In this case there is no exit code, though a signal is present. With this PR test runs are rejected with an appropriate error message, rather than the misleading "no test results received" message.
I've also cleaned up now redundant Node 0.10 SIGTERM handling (#155) and added a test for the existing test run rejection behavior.

Reject test runs when forks exit with an unexpected signal

---

code-of-conduct.md
contributing.md
docs/recipes/browser-testing.md
docs/recipes/code-coverage.md
docs/recipes/endpoint-testing.md
docs/recipes/typescript.md
docs/recipes/watch-mode.md
docs/recipes/when-to-use-plan.md
readme.md

Hi, 
I have translated the doc to Simplified Chinese (zh_CN) in [this merged PR](https://github.com/sindresorhus/ava-docs/pull/17). Now I add zh_CN link in the docs, please review. 
Thanks.

doc: add Simplified Chinese translation link in docs

---

docs/recipes/typescript.md

Once this [pull request](https://github.com/sindresorhus/ava-docs/pull/16) its merged, this link will redirect to the Spanish translation.

Add link to Spanish translation for TypeScript recipee

---

api.js
test/api.js

This PR fixes #691 by throwing an error if `resolve-cwd` returns `null`.

throw error if required dependency could not be found - fixes #691

---

index.d.ts
lib/assert.js
lib/enhance-assert.js
readme.md
test/assert.js
test/fixture/circular-reference-on-assertion.js
test/fixture/pkg-conf/defaults/test.js
test/fixture/pkg-conf/pkg-overrides/actual.js
test/fixture/pkg-conf/precedence/c.js
test/fixture/serial.js
test/hooks.js
test/test.js

Do not merge :-)
This is a work in progress PR just to get the conversation started. There are several tests that are failing and I could use some help there I think.
Thoughts?

rename `t.same()` to `t.deepEqual()`

---

lib/caching-precompiler.js
test/caching-precompiler.js

Reimplementation of #675 after recent changes, with an added test. Thanks to @dcousineau for finding the bug.

Don't modify configured babel plugins array

---

lib/caching-precompiler.js
package.json

Bump convert-source-map dependency, clean up duplicate require call

---

test/api.js
test/fixture/babel-plugin-foo-to-bar.js
test/fixture/babel-plugin-test-capitalizer.js
test/fixture/babelrc/.alt-babelrc
test/fixture/babelrc/.babelrc
test/fixture/babelrc/test.js

Issue #448 was kept open, in part, because we wanted to enable an `extends` option.
What we are after is actually possible using existing babel options.
A separate PR with recipes is forthcoming.

add tests that demonstrate various ways to use babel config.

---

docs/recipes/babelrc.md
readme.md
test/api.js
test/fixture/babel-plugin-foo-to-bar.js
test/fixture/babel-plugin-test-capitalizer.js
test/fixture/babelrc/.alt-babelrc
test/fixture/babelrc/.babelrc
test/fixture/babelrc/test.js

Tests verifying all these recommendations were added to the test suite in #706.
I think this is enough to close #448

Add a recipe for configuring `.babelrc`.

---

index.d.ts
lib/assert.js
lib/enhance-assert.js
readme.md
test/api.js
test/assert.js
test/cli.js
test/fixture/one-pass-one-fail.js
test/fixture/power-assert.js
test/fixture/slow-exit.js

Pretty confident that this is ready to go.

rename `t.ok()` to `t.truthy()` and `t.notOk()` to `t.falsy()`

---

lib/watcher.js
test/watcher.js

The watcher used `dir**/*.js` as the recursive pattern when the initial pattern matched a directory. This should be `dir/**/*.js` instead. Before this fix tests were matched as sources, causing all tests to be rerun.

watcher: fix recursive test file matcher

---

lib/reporters/mini.js
test/reporters/mini.js

This helps with #575. Kinda.
First as @novemberborn said:
> If we can agree that these are not fatal errors then I think we can fix up the reporters.
But if we agree to do them in the reporters, I fixed up the extraneous new lines and added a cross for `AvaError` type of exceptions.
Here's how test on a nonexistent file and a regular one looks like:
Also there are a lot of places I could've chosen to remove newlines from, so tell me if there are any better ones (I did this quickly to see what you guys think!).

Add test-like output when test file does not exist

---

lib/runner.js
readme.md
test/runner.js

This was suggested in #705. Let me know if I missed anything or if there's a better word.

Replace "callback" with "implementation" when talking about tests

---

docs/recipes/watch-mode.md

Thanks @forresst for [pointing out](https://github.com/sindresorhus/ava/commit/e57908a91aad0e875c8a2ca9157edc7c4e0840b5#commitcomment-17001621) I dropped the link during editing.

add missing link to .only modifier in watch mode recipe

---

lib/runner.js
test/hooks.js
test/runner.js

Follow-up to #654. No longer collecting stats for every test that completes. Explicitly return `null` when no exclusive tests could be run.

clean up stat collection in runner

---

cli.js
lib/ava-files.js
readme.md

This PR just updates documentation. I couldn't for the life of me find out where this magic happens. Pointers? Thanks!

Support more test filename conventions

---

docs/recipes/babelrc.md
lib/caching-precompiler.js
lib/fork.js
lib/test-worker.js
lib/test.js
lib/throws-helper.js
package.json
readme.md
test/caching-precompiler.js
test/cli.js
test/fixture/improper-t-throws-async-callback.js
test/fixture/improper-t-throws-promise.js
test/fixture/improper-t-throws-unhandled-rejection.js
test/fixture/improper-t-throws.js

Protects against a common misuse of t.throws (Like that seen in #739).
This required the creation of a custom babel plugin.
https://github.com/jamestalmage/babel-plugin-ava-throws-helper
Sample output:
```
Improper usage of t.throws detected at /Users/jamestalmage/dev/ava/test/fixture/improper-t-throws.js (4:10).
You should wrap the following expression in a function:
throwSync()
Like this:
function() {
throwSync()
}
See https://github.com/sindresorhus/ava#throwsfunctionpromise-error-message for more details.
```
The linked documentation isn't that helpful. We should probably make a short recipe about this. (maybe a `common-mistakes` recipe? This seems like too small a topic for a whole recipe). We can update the URL when that recipe is written.

detect improper use of t.throws

---

docs/recipes/watch-mode.md
lib/watcher.js
test/watcher.js

Bugfix where `..file.js` sources were treated as being outside the current working directory. But the main change of this PR is that negated source patterns are now handled much better :boom: 
Fixes #614. Allow negated source patterns to be specified without unsetting the default negation patterns.
Allow source patterns to override the default negation patterns if they start with one of the ignored directories.

Improve source pattern handling

---

lib/logger.js
lib/reporters/mini.js
lib/reporters/verbose.js
lib/watcher.js
package.json
test/cli.js
test/helper/compare-line-output.js
test/logger.js
test/reporters/mini.js
test/reporters/verbose.js
test/watcher.js

Fixes #670.
* When the mini and verbose reporters finish, add a timestamp after the first passed/failed/etc status line
* Ensure the watcher doesn't break the mini reporter's spinner on the first run
* Ensure the watcher restarts the mini reporter's spinner on subsequent runs
* Clear the mini reporter on subsequent runs, unless failures occurred or `r\n` was entered on stdin (because that inserts a line which can't be cleared)
Also includes some test improvements.

Improve watch logging

---

lib/watcher.js
test/cli.js
test/fixture/watcher/with-dependencies/source.js
test/fixture/watcher/with-dependencies/test-1.js
test/fixture/watcher/with-dependencies/test-2.js
test/watcher.js

Since #713 the API no longer emits 'dependencies' events. These are emitted instead by the RunStatus, which can be obtained by listening to the 'test-run' event on the API.
The watcher tests use a mocked API object which wasn't updated to reflect these changes. Consequently dependency tracking was broken since #713 was merged.
This commit fixes the watcher and the corresponding tests. I've also added an integration test which does not rely on mocking, helping us detect breakage sooner.

Ensure watcher receives dependencies again

---

lib/watcher.js
test/watcher.js

Don't clear the reporter if the previous run had exceptions or rejections.
Improve the stubbing of the run status in the tests.

watcher: improve clearance avoidance

---

test/reporters/mini.js
test/reporters/verbose.js

This mocks time using the region dependent Date constructor, so reporter output always shows the same time regardless.
non-controversial, so I will be merging as soon as I verify Travis passes

Fix region dependent test failures.

---

api.js
lib/reporters/mini.js
lib/reporters/verbose.js
lib/run-status.js
lib/watcher.js
test/api.js
test/reporters/mini.js
test/reporters/verbose.js
test/watcher.js

Fixes #699. The watcher tracks how many failures (actual failures, but also rejections and uncaught exceptions) occurred for each test file. After each run, if there are failures from files that were not rerun, the count is added to the logger output.

	watcher: remember failures from previous tests

---

readme.md

There was a trailing comma after the es2015 "presets" key.

presets example documentation fix

---

readme.md

The sample CLI output in the readme was presumably copied from the source in cli.js, but a single quote and comma seems to have been left behind.

Removed stray characters from CLI sample output

---

docs/recipes/when-to-use-plan.md

Updates the recipe surrounding proper uses of `t.plan()` due to improved `t.throws()` behavior.
https://github.com/sindresorhus/ava/issues/749

Docs: update t.plan recipe. `Fixes #749`

---

lib/caching-precompiler.js
package.json

I just wrote <https://github.com/novemberborn/package-hash> which is a more powerful way of computing hashes for packages. It includes the GIt repo state which is very useful during development. Say if you're hacking on AVA and `npm link` it into a test project, now you don't need to clear the AVA cache in your test project whenever you make changes to AVA.
Feedback welcome!

compute cache salt using package-hash

---

lib/test.js
test/test.js

Throwing synchronously inside a callback style test should fail it immediately.

---

package.json

Hi
Looking at the `ava` dependencies I spotted a double `babel-code-frame` [L86](https://github.com/sindresorhus/ava/blob/d6acdde056238d5e7403e63413b63a39dd61ff6a/package.json#L86) and [L151](https://github.com/sindresorhus/ava/blob/d6acdde056238d5e7403e63413b63a39dd61ff6a/package.json#L151)
No problem with removing the one in the devDependencies ?

chore(pkg): remove duplicate babel-code-frame dependency

---

docs/recipes/react.md
readme.md

Fixes #446
Hi!
Here is a first attempt to a React recipe. I'm not a native english speaker so, please carefully read the whole recipe and fix my grammar :stuck_out_tongue: : https://github.com/adriantoine/ava/blob/master/docs/recipes/react.md
I might have forgotten something, please let me know!
Also, as a native french speaker, I'll be happy to make the translation to French once this is merged.

React recipe

---

lib/reporters/tap.js
package.json
test/reporters/tap.js

Fixes issue mentioned by @xjamundx in #723.

Strip ANSI escape codes in TAP test titles

---

lib/fork.js

Fixes #814, but causes all sorts of test breakage.
I can't really figure out why it breaks the tests, it seems to work fine IRL. My only guess is that being wrapped by `tap` is somehow causing the problem.

Fix `npm link` usage on Node.js 6

---

lib/runner.js
lib/test-collection.js
readme.md
test/hooks.js
test/test-collection.js

This pull request aims at #474 .
The new tests added in `test/hooks.js` passed, but these changes lead to other tests' failure.
Still working on figuring out why, comments are welcome!

add `after.always` and `afterEach.always` hooks - fixes #474

---

lib/test-worker.js
test/api.js
test/fixture/source-map-file-browser-env.js

closes #822 
- I've added a failing test. basically just copied one of the existing source map fixtures and added the two lines that make `source-map-support` think it's a browser env. I'm not sure I added the test in the right place, do let me know if it should go somewhere else.
```js
global.window = function () {};
global.XMLHttpRequest = function () {};
```
- I've also added the option @novemberborn mentioned on https://github.com/sindresorhus/ava/issues/822#issuecomment-218703506 to `sourceMapSupport.install()` to fix the bug

fix crash in 'fake' browser env

---

lib/runner.js
lib/test.js
readme.md
test/test.js

[WIP] A way to submit tests that should fail.

---

lib/test.js
readme.md
test/test.js

Follow-up to #831.

---

lib/assert.js
test/assert.js
test/test.js

If a non-function, non-promise, non-observable argument (i.e. a string)  is passed to `t.throws`, the assertion passes. This obviously isn't what we want.

Protect against bad argument passed to t.throws.

---

lib/runner.js
readme.md
test/runner.js

This adds basic macro support as discussed in #695.
It does not completely implement the spec outlined there, specifically:
- The macro can only specify the title using a function in `macroFn.title`. We discussed allowing `macroFn.title` to also be a string, and allowing some form of template language for extracting a title. However, using ES2015 string templates is already pretty easy, so we may just skip this.
- ~~We discussed allowing an array of macro functions.~~
Both the above proposals are found in [this comment](https://github.com/sindresorhus/ava/issues/695#issuecomment-205929738). They both enhance the implementation found in this commit, and would not break the contract. So I don't think there is anything preventing us from shipping this now.

Basic macro support.

---

api.js
test/cli.js

on master running `ava blah` assuming `blah` matches no files will fail like this 
instead of like this, as it should
This happens because when no files are found `Api.prototype.run` is returning an empty array instead of `runStatus`. So it then fails in the reporter, which in its `finish` method expects its argument to be an instance of `runStatus` instead of an empty array

api#run should return runStatus even when no files are found

---

lib/ava-files.js
lib/watcher.js
test/ava-files.js
test/watcher.js

So far I've only moved some of the path processing stuff into AvaFiles.

[WIP]: refactor watcher

---

lib/run-status.js
test/run-status.js

When `this.base` is `/` it ends up replacing the first `/`, joining the first two directories.
Before this change it  #looked like this:
(notice no separator between `backend` and `models`)
But it should look like this:
Unless I misunderstood `this.base` it should only be replaced if that's what the path begins with.
I didn't add any test because there's no test file for `run-status.js`

RunStatus#prefixTitle should remove this.base only if it occurs at the beginning of the path

---

index.d.ts

Hey guys,
first of all thanks for this awesome testrunner.
I've added the missing todo definition to the index.d.ts.

[typescript] added missing todo definition

---

api.js
lib/reporters/mini.js
lib/reporters/verbose.js
lib/run-status.js
lib/runner.js
lib/test.js
test/reporters/mini.js
test/reporters/verbose.js
test/test.js

add output for failing tests

---

lib/ava-files.js

Improves globbing performance.
From the [`node-glob` docs](https://github.com/isaacs/node-glob#options):
> At the very least, you may pass in shared symlinks, statCache, realpathCache, and cache options, so that parallel glob operations will be sped up by sharing information about the filesystem.

Pass shared caches to `globby`.

---

index.js
test/cli.js

We used to have a nice warning, telling people to use the CLI if they ran `node path/to/testfile.js`. It was broken by requiring `test-worker` to early. `test-worker` tries `JSON.parse(process.argv[2])`, which will likely throw. Preventing the helpful message.
This adds a fix, and a regression test.

Fix "Test files must be run with the AVA CLI warning".

---

lib/fork.js

This mostly reverts #815, and #827. The Node regressions they fixed were resolved in Node 6.2.0. The new behavior is just to print a warning message so people know how to fix it.

revert npm link fix.

---

lib/fork.js

It's not used anywhere. I think we've refactored out all the tests that used to use it.

Drop unused `silent` option from `lib/fork.js`.

---

readme.md

document always hook with fail fast flag

---

index.d.ts

Added the declaration for [test.failing](https://github.com/avajs/ava#failing-tests) and fixed `test.serial`. It now allows you to write `test.serial.cb`.
I'm not sure if this is possible?
- `test.cb.serial`
- `test.cb.failing`
But I don't think it is and it is not allowed at the moment.

add test.failing and add cb to test.serial

---

index.d.ts

`after.always` and `afterEach.always` runners were added to ava in 0.15.  I added them to `index.d.ts`.  I already confirmed that below code can be compiled with new `index.d.ts`.
```typescript
import test from 'ava';
test.afterEach(t => {
console.log('BEFORE');
});
test.afterEach.always(t => {
console.log('BEFORE ALWAYS');
});
test.after(t => {
console.log('AFTER');
});
test.after.always(t => {
console.log('AFTER ALWAYS');
});
```

Add after.always afterEach.always runners to index.d.ts

---

docs/recipes/typescript.md

Following the old example didn't work for me. It appears the new recommended way to install `tsc` is just to install `typescript`.

Fix TypeScript recipe.

---

test/api.js

the `endWithMap` function had the wrong regex

fix typo in test/api.js

---

lib/run-status.js
lib/test.js
test/api.js

- removed power assert formatter usage from `run-status.js`
- onError function passed to `enhanceAssert` in `test.js` now replaces message on `Error` object if there is `powerAssertContext` and does not attach `powerAssertContext` to the error anymore.
- removed assertion from test in `test/api.js` that assumed errors had `powerAssertContext`.

move power assert error message formatting to child processes

---

lib/watcher.js
package.json

Follow-up to <https://github.com/avajs/ava/pull/869#issuecomment-221456875>. `arr-diff@3` mutates the input array. `lodash.difference` is a drop-in replacement.

Swap arr-diff for lodash.difference

---

docs/recipes/react.md

When using JSX in test code, you need to enable the react preset, even if you already do so as part of your general babel config.
The current docs use JSX in the test, but have no babel presets in the `ava` config.
Setting the `babel` option to `"inherit"` (to pick up the babel config set in the same file) does the trick.

Fix babel settings for jsx in test files

---

docs/recipes/watch-mode.md
lib/watcher.js
package.json
test/cli.js
test/watcher.js

Fixes #913 
Changes made according to the instructions in #913
Todo (or not):

Chokidar shouldn't be an optional dependency

---

readme.md

readme: add note about uncaught exceptions

---

cli.js
lib/babel-config.js
lib/caching-precompiler.js
test/bable-config.js
test/caching-precompiler.js

This adds `lib/babel-config.js`, it is used to:
1. Validate the `babel` option in `package.json` (i.e. make sure it's either `"default"`, `"inherit"`, or an `Object`). We were doing this in `cli.js`, which was definitely not the right place to do it.
2. Build a babel config which is passed to `babel.transform`. This was previously done in `caching-precompiler`. That didn't make much sense either, `caching-precompiler` should be dedicated to handling the caching, not options manipulation.

Extract babel config generation into it's own submodule

---

docs/recipes/react.md

Adds recipe to test **React components** in Spanish! :es:
Should be merged when https://github.com/avajs/ava-docs/pull/31 is merged first. :wink:

Translate React recipe to Spanish (es_ES)

---

lib/runner.js
test/runner.js

This is my first pull request so any feedback is welcome.
fixes #948 
Added a test in the runner test file which expects an error to be thrown when test is called in a test. I don't know if this is the right file to put this test, but it seem like a good place since my solution only changed the runner.js file.
My solution was to add a new property to runner called 'hasBegunRunning' which is set to true in the run method. The chaining function checks this property and throws an error when it is true.
I don't know if this is a good solution but it is simple and it works. Also, I don't know if I need more tests for this pull request.

prevent nested tests #948

---

types/base.d.ts

Allows using AVA with Typescript's `noImplicitAny` restriction enabled.
// @ivogabe @SamVerschueren

Add parameter types to notRegex in Typescript definition

---

cli.js

This PR fixes #984.
Thanks to @eugirdor for reporting the issue and for the fix.

Fix broken CLI on Windows

---

types/base.d.ts
types/make.js

This brings support for [test macros](https://github.com/avajs/ava#test-macros) in the typescript.
It adds a macro interface, overloads the test function definition, and overloads all combinations of test modifiers.
Similar to #895 but built on top of #884

support test macros in typescript definitions

---

api.js
lib/fork.js
package.json
test/api.js
test/fixture/debug-arg.js

Continue #613
More robust and maintainable approach was found. Just compute required data before main promise for all files. So, it is simple to add new function in to the existing promise chain. Yeah, I spend a lot of time trying to fix last failed test and decided to rework solution.
> This also doesn't handle the case where the user would do --debug-brk 213 instead of --debug-brk=213.
> https://github.com/avajs/ava/pull/613#discussion_r55246479
This syntax is not supported because node supports only `--debug=`, but not `--debug <port number>`.
```
develar-work:~ develar$ node --debug 12334 foo.js
Debugger listening on port 5858
module.js:442
throw err;
^
Error: Cannot find module '/Users/develar/12334'
```
> Can you add some tests?
> …

set child process debug port to an available port - fixes #342

---

test/assert.js

Additional tests for deepEqual:
* Empty array and empty object do not match
* Array and object do not match
Related #992

Improve tests for deepEqual

---

lib/assert.js

This fixes issue #995. This is my first AVA contribution, any feedback would be appreciated.

Deprecate `t.error()` - fixes #995

---

types/make.js

This small fix fixes #1004. The statement was wrong as it provided a context to `before` and `after` but not to `beforeEach` and `afterEach`.
// @ivogabe

fix context in beforeEach and afterEach hooks - fixes #1004

---

docs/recipes/debugging-with-webstorm.md

WebStorm recipe

---

package.json
test/api.js
test/assert.js
test/concurrent.js
test/fork.js
test/hooks.js

Fixes #935.
Added `return` when a test finished with a promise and didn't use `t.end`.
There's probably stuff I missed, so let me know!

Upgrade tap and ensure asynchronous tests return promises 

---

docs/common-pitfalls.md

Mention `eslint-plugin-ava` in the common pitfalls docs. Let me know if you want a different wording ;)
Fixes https://github.com/avajs/ava/issues/404#issuecomment-238175914

Mention `eslint-plugin-ava` in the common pitfalls docs

---

index.js.flow
package.json

Resolves #986
I wanted to test Flow against one of AVA's test files but it looks like the test suite isn't self-hosted and there doesn't appear to be any integration-like tests for the public api.
I would suggest doing something along those lines and testing both Flow and TypeScript against it, otherwise you'll end up with out of date type definitions like what has already happened with the TS definition and `.always`

Add Flow type definition

---

docs/common-pitfalls.md

General update of the async section and document takeaways from #567.

Document more async pitfalls

---

readme.md

The docs say that `t` is the only argument passed to tests. Since macros arrived, that is not true anymore.

Do not say that `t` is the only argument of a test

---

docs/recipes/browser-testing.md

Fixes https://github.com/avajs/ava/issues/882

Replace `jsdom` with `browser-env` in browser recipe

---

api.js
test/api.js

Starting a series of "cleaning up" PRs to make AVA's codebase cleaner and friendlier to everyone. These PRs don't change any functionality and don't modify tests on purpose, those are just code improvements.
This PR removes lots of nesting, nested functions (`tryRun()`, `run()`, `runner()`) and confusing code. Also, it brings little improvements in the naming, options objects and makes functions shorter by extracting their parts into individual functions.

Clean up API

---

cli.js
docs/recipes/code-coverage.md
docs/recipes/watch-mode.md
profile.js
readme.md
test/cli.js
test/fixture/pkg-conf/pkg-overrides/actual.js
test/fixture/pkg-conf/precedence/c.js

This completes #1069 as part of #1048 - removes `--require`/`-r` from the CLI interface, corrects documentation where relevant, modifies CLI tests accordingly.
Not sure if it makes sense to add a deprecation notice or any clarifications to docs - these changes remove mentions of the flag and defer to `package.json` configuration guidelines.

Remove --require CLI option (completes #1069)

---

docs/recipes/watch-mode.md

Fix link to configuration in readme

---

api.js
lib/caching-precompiler.js
profile.js
test/caching-precompiler.js
test/fork.js
test/hooks.js

Tiny clean up of `lib/caching-precompiler.js`.
Changes:
- No boolean args in constructor, provide options object instead.
- Make hash generation parts more clearer.
- Rename `_factory` method, which was a bit confusing (at least to me).

Clean up caching precompiler

---

.travis.yml
appveyor.yml

Inspired by <https://twitter.com/kentcdodds/status/786282951210262528> I looked into caching npm and `node_modules`, which led to some more improvements:
* Stop testing Node.js v5
* In Travis, only install latest npm if the Node.js version is older than v6 (though I suppose when v4 ships we may want to change that again, or actually force it to install v3)
* Cache npm cache and `node_modules` in both Travis and Appveyor
* Clean up Appveyor config a little
On Travis the first, non-cached run took 5m59s. The second run took 4m15s. I think it saves on nyc instrumentation too since that's cached in `node_modules`. On Appveyor the time went from 13m3s to 9m30s (note that Appveyor doesn't run builds in parallel for us).

Speed up CI

---

docs/common-pitfalls.md
readme.md

- Reworded the statement in the readme regarding the first parameter needing to be `t` to make it stronger and explain why its required.
- Add a note in common-pitfalls regarding the same issue
- Make the indentation style consistent in the code samples 
Closes #1031

Add docs for test parameter need to be named `t`

---

docs/recipes/debugging-with-chrome-devtools.md
readme.md

Please do not mark this as a fix for #1112.
I have another PR coming for that.

docs: recipe to debug with DevTools

---

lib/reporters/mini.js
test/reporters/mini.js

This PR increases code coverage #161  in mini-reporter by removing unused code and added a new test to verify the behaviour.
The removed if-statement seems to be unnecessary because the same value is check in the beginning of the function.

Removed unused code in mini reporter and added test to verify behaviour

---

index.js.flow

Fixes #1114
As reported in #1114, flow reports ambiguity when defining tests:
```js
test('my test', t => {})
```
Flow will report that it could apply either the `Test` type or the `Macro` type. The `Test` type is an obvious fit, but `Macro` also applies since the `...args` resolves to the empty array, and the optional `title?` attribute happens to be not provided.
My suggested fix is to merge the `Test` and `Macro` types together since `Macro` is really a superset of the `Test` type, and we don't lose any type safety by just expecting to always get Macros.
I tested this locally on a flow-typed repository and confirmed that the type ambiguity errors are solved.

Fix Flow type ambiguity

---

docs/recipes/endpoint-testing.md

Hi! :wave: The `endpoint-testing` recipe mentions using SuperTest-as-promised, but it's deprecated since SuperTest now supports Promises itself.
See https://github.com/visionmedia/supertest/blob/master/History.md#200--2016-07-29
Thanks for y'all's work on Ava, it's great :tada:

Supertest ^2.0.0 supports Promises by default

---

api.js
lib/colors.js
lib/reporters/mini.js
lib/reporters/verbose.js
lib/run-status.js
test/reporters/mini.js
test/reporters/verbose.js

Hi there,
This PR fixes #1134. If --fail-fast is enabled it will print out the following message at the end of the report for both mini and verbose.
> `--fail-fast` is on. Any number of tests may have been skipped
**Mini:**
**Verbose:**
This works for now, but i´m not sure if the way I have done it is the best. 
I have been thinking that maybe instead of going through all the results in run-status looking for a stat element that has failFastEnabled=true. 
It might be better to send a event or something if the Runner is created with the fail-fast option enabled. Then run-status could pickup on this and just set:
this.failFastEnabled = true
Let me know what you guys think!
Also i appreciate the support in the issue section helping me out with this :)

Print out warning in verbose & mini reporter when `--fail-fast` is enabled

---

api.js
readme.md
test/api.js
test/fixture/precompile-helpers/test/_b.js
test/fixture/precompile-helpers/test/helpers/a.js
test/fixture/precompile-helpers/test/test.js

Fixes #720 and potentially #1049.
Lack of this feature has been bugging me for a long time, glad I've finally found a time to fix it. It's still WIP, need to:
As for #1049 (external macros are not precompiled), we could add a special glob for that, like `**/macros/**` to precompile those files as well.

Precompile helpers

---

index.js.flow
types/base.d.ts

The signature for the two assertions `t.true()` and `t.false()` requires the first parameter to be a `boolean` ([Link to relevant lines](https://github.com/avajs/ava/blob/8816faf6bee675213c5bfe32f628a0a683708484/types/base.d.ts#L43-L50)). This makes it cumbersome to tests if a `function` returns `true` or another non-`boolean` value.
Using `t.truthy()` or `t.falsy()` instead doesn't entirely solve this, if the function must return a `boolean` and not just something ... truthy/falsy. The below example illustrates the issue.
> This patch changes the signature of the two assertions `t.true()` and `t.false()` to `any`/`mixed` in order to allow a more convenient way to test for the exact outcome.
```ts
const isNumber = x => typeof x === 'number' ? true: Error('Not a number'); …
```

Signature of assertions true/false for flow/TS

---

docs/specs/001 - Improving language support.md

An [RFC](http://blog.npmjs.org/post/153881413635/some-notes-on-rfcs) with a proposal for improving AVA's support for Babel, React and TypeScript projects.
We'll leave this open as a PR for a while to gather feedback. If accepted this incorporates / supersedes #707, #1082, #945, #631 and #1122.

RFC 001: Improving language support

---

lib/colors.js
lib/main.js
lib/reporters/mini.js
lib/reporters/verbose.js
lib/run-status.js
lib/test-collection.js
test/api.js
test/reporters/mini.js
test/reporters/verbose.js
test/run-status.js

This PR fixes #1135. If all test files have at least one .only test in them, it will print out the following message at the end of the report for both mini and verbose.
> The .only() modifier is used in some tests. All other tests have been skipped.
If there are test files without .only in them, it will print out the following.
> The .only() modifier is used in some tests. At least', remainingTests, 'tests were not run.
remainingTests will then be the number of tests in the test files that don´t have any .only tests.
It currently looks like this:
Feedback appreciated :)

Print out warning in verbose & mini reporter when .only() tests are used

---

lib/reporters/mini.js
lib/reporters/verbose.js
test/reporters/mini.js
test/reporters/verbose.js

@novemberborn tiny PR to fix the period in the end of exclusive / only()  report in mini and verbose reporters.
Requested by @novemberborn after PR #1177 was closed.

Removed period at end of only()/exclusive output in mini and verbose reporters

---

lib/reporters/mini.js
lib/reporters/verbose.js
test/reporters/mini.js
test/reporters/verbose.js

This PR tries to fix #1171 by calculating the remaningCount in run-status.js
And then check the value in the reporters, if there are no remaining test it will not print:
> `--fail-fast` is on. Any number of tests may have been skipped

Only print fail-fast when there are remaining tests

---

docs/common-pitfalls.md

is-ci moved the logic for detecting the CI server to the ci-info module, see https://github.com/watson/is-ci/commit/b78b21179f39c716e1702927ca25bc759fb61b1f.
Alternatively, we could also drop that part of the sentence and just link to is-ci.

Update link to is-ci’s environment variables

---

docs/recipes/watch-mode.md
lib/cli.js
readme.md
test/cli.js

Removed every reference within `lib/cli.js`.  Replaced the reference for the `Watcher` constructor with `conf.source`.
I don't know if I need to write some tests or there are other references to remove, I tried to check what seemed more relevant.

Removed --source, -S CLI flag. Fixes #937

---

index.js.flow

Instead of double-defining each of these, define them once while using overloading.
Also took some liberties to improve the definition. Specifically, ava doesn't care what values these throwing functions return, but doesn't produce a return value.
Fixes #1148

Fix flow errors using t.throws and t.notThrows

---

lib/reporters/mini.js
lib/reporters/verbose.js
test/reporters/mini.js
test/reporters/verbose.js

I'm back @avajs/core!
Closes #1172.
Let me know if you want to change the text.

Show how many tests were skipped by --fail-fast

---

.flowconfig
index.js.flow
package.json
test/flow-types/regression-1114.js.flow
test/flow-types/regression-1148.js.flow

Closes #1224
This adds flow-bin, adds it to the test running script, and adds some regression tests based on prior issues.
In an immediate proof of value (and proof of my own prior sloppiness) it spotted an issue that #1219 sought to fix and did not do so. Fix included along with test.

Add flow type tests

---

lib/babel-config.js
lib/cli.js
lib/fork.js
lib/reporters/mini.js
lib/reporters/verbose.js
readme.md
test/cli.js
test/reporters/mini.js
test/reporters/verbose.js

Started working on fixing #843. So far I have managed to disable color output for both mini and verbose reporters by setting the --no-color flag. 
Now I need to disable color output also if you try console.log with colors inside a test. What I am a little stuck on at the moment is this spawning of child processes. Thats a part of the code base I have yet to understand.
Any pointers on where to start digging? :)

Added support for --no-color flag in verbose and mini reporters

---

types/base.d.ts

The snapshot method was missing in the typescript type-definition file.

Add TypeScript definition for the snapshot assertion

---

api.js

The way helpers are precompiled, if you invoke AVA from inside a directory, with file arguments, then only helper files inside that directory are precompiled.
We'll be able to fix it when we move compilation into the workers, and I'm not even convinced it should be considered a bug at this stage. I did want to document the behavior somewhere, but I'm not sure it has to be in user-facing documentation as it's (hopefully) a rather specific edge-case.

Document helper precompilation caveat (in code at least)

---

api.js
lib/cli.js
lib/fork.js
test/api.js

* Rename pkgDir to projectDir: this better communicates it's the
directory of the user's project.
* Remove unused cwd option from API.
* Remove default for resolveTestsFrom. It's confusing to see
process.cwd() in the code even though it's never actually used.
* Ensure API test properly creates the API instances.

Clarify directories used by API

---

test/api.js

We're ending up compiling all helper-like files in AVA's test/ directory, which is unnecessary.
Builds on https://github.com/avajs/ava/pull/1252 (which is the base for this PR).

Avoid helper compilation during API tests

---

test/reporters/tap.js

Stub process.stderr.write(), rather than just spying on it. Otherwise 'resultresult' gets written to the stderr while the tests run.

Ensure TAP reporter test does not write to stderr

---

lib/reporters/mini.js
lib/reporters/verbose.js
test/reporters/mini.js
test/reporters/verbose.js

The idea is to check when the `test.error.source.file` is NOT the same of the `test.file` within the `forEach` of the errors.
I saw that when I throw an error from another module the `test.file` refers to the module's file and not the file that is running the test.
In this case for example if I make this check, I'm able to hide the stack trace.
```sh
1 failed
lol.js:2
1: const testing = () => { 
2:   throw new Error('lol')
3: }                       
Error: lol
testing (lol.js:2:8)
Test.t [as fn] (test.js:5:2)
```
Waiting for your feedback to move forward!

Simplify failure output - fixes #1072

---

lib/watcher.js

The watcher would break if `logger.finish()` threw an exception. Instead rethrow this error (which causes the process to exit).
This surfaced in https://github.com/avajs/ava/issues/1231#issuecomment-278169455.

Ensure watcher rethrows logger errors

---

docs/recipes/babelrc.md

Babelrc recipe cleanup

---

lib/main.js
lib/test-worker.js
lib/test.js
test/cli.js
test/fixture/trigger-worker-exception/hack.js
test/fixture/trigger-worker-exception/package.json
test/fixture/trigger-worker-exception/test-fallback.js
test/fixture/trigger-worker-exception/test.js

The first commit is there to catch more errors. The second commit ensures errors like https://github.com/avajs/ava/issues/1263 are surfaced without the test hanging.

Ensure test run failures crash worker

---

lib/serialize-error.js
package.json
readme.md
test/serialize-error.js

Fixes #1233. Our assertions don't call toJSON(), so we shouldn't use it either when displaying actual and expected values.
Also:
* Bump `@ava/pretty-format` to include bug fixes
* Document that `deepEqual()` uses `lodash.isequal`

Don't call toJSON() when formatting values

---

package.json
test/flow-types/.flowconfig
test/flow-types/regression-1114.js.flow
test/flow-types/regression-1148.js.flow

`flow check` is easily taking 30 seconds on my development machine, presumably it's checking too many files. Move the `.flowconfig` into the flow-types test directory and only include the `index.js.flow` file to improve check speed.
I've verified it still catches type errors by reverting the `notThrows` fix from #1230.
@leebyron does my analysis make sense? Given how the `ignore` expressions work I don't think there's any other way of restricting `flow check` to just the three `.js.flow` files we currently have.

Speed up flow check

---

test/cli.js
test/fixture/babel-hook-imported.js

Node.js 7.6.0 supports async / await so the test doesn't throw an exception. Use the unsupported module syntax instead.

Fix Babel require hook test for Node.js 7.6.0

---

lib/format-assert-error.js
test/format-assert-error.js

Make sure all string diff output is red by default.
Resolves https://github.com/avajs/ava/issues/1286

Fix string diff colours

---

lib/format-assert-error.js
package.json

Resolves https://github.com/avajs/ava/issues/1280
`diff` is really slow for large strings. This just swaps out the `diff` npm package for `diff-match-patch` which is waaaay quicker. Down from ~20mins to ~1.5s in the linked issue.

Use `diff-match-patch` for text diffs

---

lib/run-status.js
lib/serialize-error.js
test/run-status.js
test/serialize-error.js

To reproduce try ava with the following test:
```js
import test from 'ava';
test(t => {
Promise.reject(1);
});
```

Fix reporter bug when rejecting non-errors

---

lib/reporters/tap.js
package.json
test/reporters/tap.js

* Properly print multiline strings (assuming \n is the line separator)
* Print additional name & message properties
* Determine 'at' value similar to serialize-error.js. Recompute since here we want the full line
* Print unhandled errors using the same logic
* Strip ANSI from actual and expected values

Improve YAML blocks in TAP reporter

---

docs/recipes/precompiling-with-webpack.md
readme.md

Add recipe for precompiling source files with webpack

---

index.js.flow
lib/assert.js
lib/enhance-assert.js
lib/format-assert-error.js
lib/reporters/mini.js
lib/reporters/tap.js
lib/reporters/verbose.js
lib/run-status.js
lib/serialize-error.js
lib/test-worker.js
lib/test.js
test/assert.js
test/format-assert-error.js
test/promise.js
test/reporters/mini.js
test/reporters/tap.js
test/reporters/verbose.js
test/run-status.js
test/serialize-error.js
test/test.js
types/base.d.ts

See commits. Behavior should be the same, aside from these changes:
* Fixes #1227 
* Fixes #1150 
* Assertions now return `undefined` rather than `null`
* Removes the undocumented `t.assertCount` getter
* All test failures (exception thrown, rejected promise returned, `t.end(error)`) are now wrapped in an assertion error, but we'll still print the actual error
* Do the same for when `t.throws()` / `t.notThrows()` are called with an improper argument. We can now even print the actual argument passed!
* In the TAP reporter, the error YAML block now has varying properties (e.g. do not assume it has `operator` or even `assertion`)
* Test serialization no longer overwrites non-standard error properties

Refactor assertions

---

lib/cli.js

Fixes #1046 
This separates out package config keys from CLI flags by picking up defaults from `conf` and passing them to `meow` as defaults. Furthermore, the resultant `cli.flags` is copied back `conf` so that it can be used elsewhere (instead of `cli.flags`).
@novemberborn The changes have been made as per our discussion about the same. Let me know if something doesn't seems like fitting in right!

Separate config keys from CLI flags

---

docs/recipes/precompiling-with-webpack.md

Fixed `nodeExternals` in `webpack.config.js` because the provided example did not work. `externals` have to be an array and `nodeExternals` is a function that must be called and not referenced.

Fix `nodeExternals` in the precompiling-with-webpack recipe

---

lib/assert.js
lib/enhance-assert.js
lib/format-assert-error.js
lib/reporters/mini.js
lib/reporters/tap.js
lib/reporters/verbose.js
lib/serialize-error.js
lib/test.js
test/api.js
test/assert.js
test/cli.js
test/format-assert-error.js
test/promise.js
test/reporters/mini.js
test/reporters/tap.js
test/reporters/verbose.js
test/serialize-error.js
test/test.js

* Cleanup and consistency changes
* Rather than printing `Actual`/`Expected`, vary those labels by the assertion, depending on whether the assertion was improperly used or failed. This creates more helpful output
* For power-assert enhanced assertions, print the assertion failure first, followed by the statement context. Limit the depth of the formatted context to just 1. Addresses #1226, #1205 and #1204. (One last improvement would be to limit the number of properties / array items shown, but we can't do that with `pretty-format`.)
* Detect improper usage of `t.regex()` / `t.notRegex()`

More assertion changes

---

test/cli.js
test/fixture/chalk-disabled.js
test/fixture/chalk-enabled.js
test/fork.js

This PR fixes a bug where the chalk module reported that the current terminal does not support colors.
'chalk' is using the 'supports-color' module which reads process.stdout.isTTY as soon as it is required. Since our process-adapter is initializing a fake TTY support, we must ensure that 'supports-color' is not executed before our fake TTY support is initialized.
I just re-arranged the `require()` statements. Also added tests for it.
Fixes #1124

Fix issue with using 'chalk' in tests

---

lib/enhance-assert.js

Fixes #1321.
Turns out we don't have any real integration tests for assertion enhancement. I don't have time to add those right now either, but at least this fixes `master`.
With the sample code from #1321:
```
❯ "$(npm bin)"/ava test.js
1 failed
[anonymous]
/private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.okeY2IXLOl/test.js:5
4:   const x = () => 'foo';
5:   t.regex(x(), /\d/);
6: });
Value must match expression:
"foo"
Regular expression:
/\d/
x()
=> "foo"
```

Fix formatValue() reference

---

lib/test.js
test/test.js

Whilst not a great way to write tests, users may end up adding more
assertions from inside a promise chain that's passed to the `t.throws()`
or `t.notThrows()` assertions. These should be counted for the plan, and
not fail the test as being extraneous.
Fixes #1327.

Allow new assertions while waiting for pending ones

---

lib/cli.js
lib/format-assert-error.js
package.json
readme.md
test/cli.js
test/fixture/formatting-color.js

Fixes #843 (https://github.com/avajs/ava/issues/843#issuecomment-290935567). Values shouldn't be highlighted during formatting if colors are disabled.
Note that this only works when colors are disabled explicitly. @sindresorhus perhaps we should change the default value of the `color` option if we can detect colors are not supported?

Don't highlight formatted values with --no-color

---

docs/recipes/babelrc.md

- Fixes #727 by describing usage of `babel-polyfill`

Improve Babel recipe

---

lib/test.js
readme.md
test/test.js

`t.throws()` and `t.notThrows()` can be called with an observable or promise. This commit forces users to wait for the assertion to complete before finishing the test. Usually this means the test has to be written like:
```js
test(async t => {
await t.throws(Promise.reject(new Error()))
})
```
Or for callback tests:
```js
test.cb(t => {
t.throws(Promise.reject(new Error())).then(t.end)
})
```
This simplifies internal logic and helps discourage code like in #1327. Anecdotally users are surprised by the previous behavior where a synchronous test worked with an asynchronous assertion (https://github.com/avajs/ava/issues/1327#issuecomment-291122432).
Fixes #1327.

Fail tests that finish with pending assertions

---

api.js

It's risky to pass a function to a map() operation, and indeed since
get-port@3.1.0 the getPort() function takes a first argument.

Fix get-port usage

---

index.js.flow
test/flow-types/regression-1114.js.flow

fix context for beforeEach and afterEach hooks in Flow type definition file

---

docs/recipes/browser-testing.md

Ok so since writing [`browser-env`](https://github.com/lukechilds/browser-env) I have come up with a cleaner solution, [`window`](https://github.com/lukechilds/window).It's been working well for me so far and resolves some of the issues raised in #1092.
However, it requires a [small code change](https://github.com/lukechilds/window#universal-testing-pattern) and is only viable for smaller modules without lots of dependencies that also require a browser environment. For other modules you'll still need `browser-env`. For that reason I think it would be best to continue to recommend `browser-env`, but highlight the issues raised in #1092 and offer `window` as a possible alternative.
Happy to change the wording, just pretty much copied it over from what I've got in the `browser-env` readme.

Add warning to browser recipe

---

lib/assert.js
readme.md
test/assert.js
test/test.js

Refactor `is` assertion to use `Object.is()` rather than `===`.
Also add a few more test cases in for `is` to make it clearer what it is expected to do.
As per discussion in #1339, this will make it more sensible to compare `NaN` against `NaN`.
The good:
- `NaN` now compares to `NaN` in a way that people expect (truthily)
The odd:
- `+0`/`0` and `-0` are now **not** equal. As we discussed in #1339, this actually feels fine - this being a testing framework, it's good to be strict on this math stuff, while sensible on the NaN stuff.
Fixes #1339 
/cc @novemberborn, @sotojuan, @sindresorhus

Make `t.is()` use `Object.is()`

---

index.js.flow

By @zs-zs, extracted from #1344 to minimize impact in a patch release.

Remove dead Flow types

---

lib/babel-config.js
test/cli.js

The readme has update to [es2017](https://github.com/avajs/ava#es2017-support).

Update Babel config link to point to "ES2017 support" section in the readme

---

docs/recipes/debugging-with-vscode.md
readme.md

A guide to debug tests with Visual Studio Code.

Recipe to debug with VSCode

---

docs/recipes/isolating-mongodb-integration-tests.md
readme.md

Includes a recipe detailing how to run isolated MongoDB tests using an in-memory MongoDB server.
Includes 'extra' steps to run with Mongoose.
As request in #807 .

MongoDB testing recipe

---

docs/recipes/vue.md
readme.md

Add Vue.js recipe

---

docs/recipes/debugging-with-vscode.md

Extended the VSCode debugging instructions with `debugger;`.

Docs: Extend VSCode debugging notes

---

lib/cli.js
test/cli.js
test/fixture/concurrency/test.js

Fail hard when `--concurrency` is used without a value

---

docs/specs/001 - Improving language support.md

Spaces no longer work with the new GH Markdown parser

Fix spec markdown link

---

.travis.yml
appveyor.yml
package.json
test/babel-config.js
test/cli.js

Highlights:
* Test on latest Node.js without a `package-lock`: this means we're testing the dependencies as seen by the user when they install AVA
* Test on all Node.js versions with a `package-lock`. This includes the latest version, which may be useful in determining whether a failure is due to a dependency or not
* Fix tests for Node.js 8.1.0
* Allow tests to take longer
* More efficient AppVeyor tests

Improve CI

---

.travis.yml
appveyor.yml
package.json

I forgot to bump the test timeout for Travis, so we were still seeing lots of failures. Caching the `node_modules` folder keeps tripping up npm installs, so instead rely on npm's tarball caching and `--prefer-offline` / `--prefer-online` flags.

More CI fixes

---

lib/assert.js
test/assert.js

Fixes #1342
Maybe the test can be written better?

Output message when `t.throws()` fails

---

docs/recipes/precompiling-with-webpack.md

Adds comments for pre-compilation of multiple test files which ava supports. Also changed the target output directory to absolute path in accordance with [webpack docs](https://webpack.js.org/configuration/)

docs(recipe): Add comments for precompiling multiple test files

---

api.js
test/api.js

On Node 8 Webstorm debug is not working any longer. The reason is, that the `--inspect-brk` is not handled correctly inside of the cli.js file
```
Starting inspector on 127.0.0.1:53733 failed: address already in use
```
Adding --inspect-brk to api.js
Node v8.1, latest AVAJS

Fix debugging with Webstorm on Node.js 8

---

api.js
docs/recipes/watch-mode.md
lib/run-status.js
lib/watcher.js
test/watcher.js

This is my humble implementation for pressing 'u' in watch mode to update snapshots.
fixes #1387

Add command for updating snapshots in watch mode

---

profile.js

Allows extra params to be passed to profile, for example when one needs to specify a different location for dotenv.  you must pass in arg in the form of `dotenv_config_path=path/to/.env`
Should not affect profiling, since only the first `cli.input[0]` is used.

Allow extra input params during profiling

---

maintaining.md

:wave: Hello!
**What**
This PR  updates the documentation, removing the outdated `coverage` script and including the `visual` script.
**Why**
When cloning the repo and setting everything up, I found about the `maintaining.md` file and tried to `npm run coverage` which gave me an error, as somebody new to the project, this was confusing.

Remove non-existent npm run script in maintaining.md

---

lib/assert.js
test/assert.js

We support AVA in wallaby.js and have a few custom renderers for displaying assertions diffs in various editors, like:
VS Code:
WebStorm:
Wallaby App:
Other testing frameworks that we support (also various assertion libs, such as `chai`) pass raw `actual` and `expected` objects with their assertion errors, so we (and other custom reporters) are able to display custom diffs.
AVA's new coloured ANSI diff display is great, but in order to display diffs outside of the ANSI supporting viewer (such as in the cases listed above), it would be great if the `AssertionError` contained raw `actual` and `expected` objects, so that a customer reporter integrated with AVA could use them for doing custom diffs/reporting (the screenshots above show how it'd look like once the PR is landed and published in …

Include raw actual and expected objects in AssertionError

---

index.js.flow

Having a specific promise resolution value of Error was causing issues
with methods that throw a custom error object.
Fixes #1442

Update flow def for AssertContext.throws to match typescript def

---

docs/recipes/debugging-with-webstorm.md

This PR extends the documentation and adds an additional recipe for running AVA in Jetbrains IDEs (Webstorm, PhpStorm etc.).

Add an additional npm-based recipe for Jetbrains IDEs

---

test/cli.js

It cannot be guaranteed that all lines output by the mini reporter are
captured in the stderr of the CLI invocation during testing. Use
--verbose when matching output that the mini reporter may otherwise
rewrite.
Somewhere on at least Node.js 8.2.1, when the package-lock.json is
discarded prior to installation, something in our dependency tree is
different which results in the test title no longer being in the stderr
of the AVA CLI.
Compare:
```
⠋ ESC[2KESC[1AESC[2KESC[G
⠙ ESC[2KESC[1AESC[2KESC[G
⠹ ESC[2KESC[1AESC[2KESC[G
⠸ ESC[2KESC[1AESC[2KESC[G
⠼ ESC[2KESC[1AESC[2KESC[G
⠴ ESC[2KESC[1AESC[2KESC[G
⠦ ESC[2KESC[1AESC[2KESC[G
⠦ test › works…
1 passedESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[G
1 passed [18:32:54]
```
Versus:
```
⠋ ESC[2KESC[1AESC[2KESC[G
⠙ ESC[2KESC[1AESC[2KESC[G
⠹ …
```

Use --verbose when testing CLI output

---

api.js
docs/common-pitfalls.md
docs/recipes/precompiling-with-webpack.md
lib/cli.js
readme.md
test/api.js

Fixes #966
This considerably improves the performance for the common case. Most users have many test files and their CPUs got overloaded. And few knew about the concurrency option.
This has the downside of making `test.only()` not be exclusive with multiple test files, but there are just too many limitations caused by it. I think this change is worth it.
I've chosen to go with a default concurrency of the number of CPU cores. We can tweak it based on real usage data later on.

Limit concurrency to the number of CPU cores

---

lib/assert.js
lib/colors.js
lib/reporters/mini.js
lib/reporters/tap.js
lib/reporters/verbose.js
lib/runner.js
lib/test.js
readme.md
test/reporters/mini.js
test/reporters/tap.js
test/reporters/verbose.js
test/test.js

There are times when you wish to include comments in your tests that will be shown in context of the test result and not streamed to `stdout` like `console.log` statements are, where they will likely be out of order of the tests they are associated with.
I will happily add tests, and change the API, etc. I just want to get general 👍 or 👎 to the concept of adding comments before I flesh out the tests and other cleanup.
One of the main use cases I have for this, is I am using ava as a runner for my SauceLabs/BrowserSrack/Selenium tests, and I would like to have the link to the job results from SauceLabs/BrowserStack be output in context with the test run. There are certainly many other usecases for this, however, just to give a relevant example of when this is useful.
```
TAP version 13 …
```

Add support for test logging

---

docs/recipes/debugging-with-webstorm.md

Update debugging with Webstorm recipe to include Node options flag --inspect-brk.

Update debugging with webstorm recipe

---

readme.md

Trivial documentation fix proposal. I think there is a typo in the example for `t.notThrows`. The test name is "rejects" but shouldn't a test with a `notThrows` assertion be checking that the promise under test resolves instead of rejects? It's confusing when compared with the example for `throws` directly above that has a test named "rejects" as well.
Cheers and thanks for Ava!

Fix typo in `t.notThrows` example

---

lib/cli.js
test/cli.js

Fixes #1476.
**Changes:**
- Added `0` check.
- Changed the message if  `concurrency` was set to an empty string, because the error message seemed a bit weird.
- Introduced an extra check to validate if `concurrency` is an integer.
- Changed default `concurrency` from `0` to `1` if no `concurrency` is given.

Fail hard when `--concurrency` is set to invalid values

---

index.js.flow
test/flow-types/regression-1500.js.flow

I updated the flow types for the snapshot function to allow an options object as a parameter.

Update snapshot signature for flow types

---

.travis.yml
appveyor.yml
package-lock.json
package.json

There's a fair bit of churn between `package-lock.json` files generated with different npm versions (even minor releases). Contributors may be using an older npm version or even Yarn. Thus the `package-lock.json` may regress or not even be updated.
~This PR proposes we pin npm to an exact version. Then in Travis we can check whether the `package-lock.json` is modified and fail the build if this occurs. This should catch regressions or missing dependencies.~
Note that CI is currently failing due to a bug in npm@5.4.0: <https://github.com/npm/npm/issues/18324>. Consequently we shouldn't land it until we can pin to a patched version.

Assume npm@5.4, work around permissions issue

---

docs/recipes/endpoint-testing-with-mongoose.md
docs/recipes/isolated-mongodb-integration-tests.md

Docs for endpoint tests. #849. 
Let me know if I'm opening the PR correctly?

Add docs for endpoint testing with mongoose 

---

lib/test-worker.js

Remove Bluebird.longStackTraces()

---

lib/runner.js
test/runner.js

<strike>(Matching on `'*'`, for example, still excludes tests with no titles, as it did prior to this commit.)</strike>
The motivation here is if I have a test suite with some anonymous tests and some titled tests, and some of the titled tests are tagged with something like `[long-running]`, and I want to run `ava -m '!*[long-running]*'`, I don't want to exclude the anonymous tests. But with current Ava they are excluded.
<strike>For what it's worth, anyone who misses the old behavior could get it back with `-m '*' -m <negative match expression(s)>`.</strike>
**Edit:** Changed so that `-m '*'` matches all tests, including anonymous. For purposes of matching, anonymous tests have empty string titles.

Match anonymous tests when all of the match expressions are negative

---

readme.md

The statement prior to this PR: _"Yarn  currently provides significant speed improvements over npm during the installation process. Consider Yarn if the installation is too slow for your needs."_
I would suggest this is no longer true with npm 5, this PR removes that statement
Secondly, I switched to npm to be the "lead" method, if you will "preffered" method to install Ava. I made this change due to my assumption that because this package now contains a `package-lock.json` file and not a `yarn.lock` file that npm 5 is now the preferred method 😏 
Edit: For reference, Yarn was added in #1130

Prioritize npm over Yarn install method in the readme

---

test/helper/colors.js
test/reporters/mini.js
test/reporters/tap.js
test/reporters/verbose.js

Stabilize colors
> Prior to this commit, the library and its tests relied on the same code
> to add color to terminal output. This prevented the tests from
> recognizing changes to that code.
> 
> Such a change was introduced in a recent release of the `chalk` module
> [1]: it was updated to disable text coloring when run without a TTY.
> This is the case in the test environment environment provided by the
> `tap` module (which Ava uses for its tests).
> 
> This fix disabled color output in the tests, but it caused no failures
> because both the expected values and the actual values were effected.
> However, this situation amounted to a decrease in test coverage because
> the expected color of the terminal output could no longer be verified.
> 
> Update the tests environment to simulate a …

Stabilize colors

---

index.js.flow
types/base.d.ts

When using Flowtype, the type validation will fail since there are is no type
declared for the newly implemented `t.log()`.
This commit adds Flowtype and TypeScript declarations for `t.log()`.

Add t.log() type for Flowtype and TypeScript

---

package.json

Fixes #1336 
Added variable `process.env.AVA_LOCAL_CLI` to show the correct message.

Version warning when local version is behind

---

docs/recipes/browser-testing.md

I didn't readily find instructions for using jquery in the browser - hopefully this helps!
(not creating a topic branch as it's a docs PR stright from GH.. is that okay?)

Recipe instructions for making jQuery available in browser

---

lib/cli.js
lib/reporters/verbose.js
test/reporters/verbose.js

Per [#1547](https://github.com/avajs/ava/issues/1547), the proposed changes update verbose output to only timestamp the first line of output when the watch option is enabled. A new unit test is provided for this feature, and failing tests (which were expecting to be timestamped) have been updated. 
Happy to field any questions or make edits. 😄  
#1547

In verbose output, only display timestamp if the watch option is enabled

---

api.js
docs/common-pitfalls.md

The new default of using CPU cores for concurrency works well most of the time, however when running tests in Docker (Travis) it will use the CPU count of the host machine, not what's been allotted to the container.
Discovered when the Got tests where timing out for no apparent reason. [I ran `os.cpus().length` on the container](https://travis-ci.org/lukechilds/got/jobs/288682178) and it returned 32. Capping at 4 resolved the issue.
This PR changes AVA to use whichever is lower out of `os.cpus().length` or `4` for concurrency by default. This seems like a sensible soft limit. You can still manually specify a concurrency that is larger than 4.

Limit concurrency to 2 in a CI environment and 8 otherwise

---

lib/enhance-assert.js
package-lock.json
package.json
test/api.js
test/fixture/enhanced-assertion-formatting.js

Fixes #1513 by using babel-generator to regenerate statements from the AST instead of concatenating tokens without whitespace. 
Note that this doesn't totally rematerialize the original syntax since the tokens included with the power assert context don't retain quote or whitespace information. This implementation outputs strings with single quotes to match the output of concordance.

Use babel-generator to regenerate enhanced assertion statements (#1513)

---

lib/test-collection.js
readme.md
test/api.js
test/fixture/hooks-skipped.js
test/test-collection.js

Attempting to fix #1283. This change removes the `before` and `after` hooks from the run sequence when all tests in the collection are skipped. It intentionally keeps the `always` hook in the run sequence, since it would probably be surprising to a user if `after.always` didn't run.

Dont run before and after hooks when all tests are skipped (#1283)

---

lib/assert.js
test/assert.js

t.is() performs deep equality check on objects and prompts to user if objects are equal.
Test for this assertion is changed.

Fixes #1553. t.is() prompts to user when objects are different references

---

.gitignore
.travis.yml
appveyor.yml
contributing.md

[npm 5.6.0](https://github.com/npm/npm/releases/tag/v5.6.0) means we can now safely test with Node.js 9, so I've added that to the test matrix.
I've also added a way of verifying the `package-lock.json` file is up to date. This should help detect unexpected or missing changes in future pull requests and reduce any churn to just when the npm version itself is updated. See https://travis-ci.org/avajs/ava/jobs/308555431 for an example of when `package-lock.json` is outdated.

Update npm, test Node.js 9, detect package-lock churn in CI

---

cli.js
lib/process-adapter.js
package-lock.json
package.json

The `time-require` package at <https://github.com/Jaguard/time-require> is unmaintained, and core bugs such as a typo `treshold` => `threshold` has had an open PR for years now at <https://github.com/Jaguard/time-require/pull/9.
I went ahead and merged that PR into a fork of the repo and published it as `@ladjs/time-require`.  As such I changed it here in ava as well through this pull request.

Switched time-require to @ladjs/time-require since main package is unmaintained

---

docs/recipes/precompiling-with-webpack.md

Fix typo in precompiling-with-webpack.md

---

types/base.d.ts

While writing my tests in TypeScript I noticed the missing overload signature for `t.snapshot(content, options [, message])`.
This add the missing type declaration.

Fix: add types for t.snapshot(content, options)

---

lib/caching-precompiler.js
package-lock.json
package.json

Fixes #817 
As far as `CachingPrecompiler` is used, `options.path` would always be assigned with absolute paths as I observed on `api.js`, `profile.js`, `fork.js`, `hooks.js`. If ever the cache directory path is not absolute, the relative map path would be added instead.
Also updated the `convert-source-map` version to `^1.5.1` as suggested.

Use absolute map paths for absolute cache paths

---

docs/recipes/debugging-with-vscode.md

Debug serially to avoid confusing execution paths in async code, e.g. swapping from one test's execution context to the next.

Debug serially in the "Debugging tests with VS Code" recipe

---

package-lock.json
package.json

Fixes #1636 
Updated code-excerpt dependency to 2.1.1 , this version contains the fix for the abnormal display on CRLF line breaks

Update code-excerpt to ^2.1.1

---

docs/recipes/babelrc.md

Fixes #1640. Add more explanation for the difference between tests vs sources babel configuration.
We may need to update the france translation later.

Add more clarification for different Babel config in .babelrc.md

---

docs/recipes/debugging-with-vscode.md

VSCode steps into native code at each `await` statement.
using skipFiles on node_internals yields a more dev-expected debug experience

docs(debugging): recommend skipFiles

---

docs/common-pitfalls.md

It adds the bug from issue https://github.com/avajs/ava/issues/1319 into the  common-pitfalls.md.

Docs : Update common-pitfalls.md with issue 1319

---

lib/assert.js
lib/main.js
test/cli.js
test/fixture/infinity-stack-trace.js

Refs: https://github.com/avajs/ava/issues/483

Dont' set `Error.stackTraceLimit` to Infinity globally

---

index.js.flow
lib/assert.js
readme.md
test/flow-types/log.js.flow
test/test.js
types/base.d.ts

Fixes #1635 
Use concordance to format all arguments except string arguments as the existing test will fail and I find it awkward this way. Update test to cater `t.log()` and `t.log(n1, n2, n3, ...)`.

Make `t.log()` behave like `console.log()`

---

index.js.flow
lib/assert.js
readme.md
test/assert.js
test/observable.js
test/promise.js
types/base.d.ts

When an async callback is given to ```t.throws()```, it will execute the function and put the returned ```Promise``` to ```promise``` variable. The rest is same as processing ```Promise```.
This commit introduce new private function ```isAsync()``` inside ```asserts.wrapAssertions()```
Refs: https://github.com/avajs/ava/issues/1371

Make `t.throws()` accept async function as parameter

---

lib/cli.js
package-lock.json
package.json
readme.md
test/cli.js
test/fixture/watcher/tap-and-watch-in-conf/package.json
test/fixture/watcher/tap-and-watch-in-conf/test.js

See commits.
Breaking changes:
* `--init`, `--watch` and `--update-snapshots` could be enabled through AVA's `package.json` configuration. This was unintentional and support has been removed
* I've renamed the `source` configuration to `sources`, to be in line with `files` which takes similar glob values and is a plural. AVA exits with an error if the old property is detected

Clean up CLI module

---

lib/ava-files.js

Share glob caches when finding test and helper files, and when rerunning all files in watch mode. This should provide a performance improvement, though I suppose certain file changes in watch mode may no longer be detected. I can't quite figure out what those would be though.

Share glob caches

---

docs/recipes/babel.md
lib/babel-config.js
package-lock.json
package.json
test/babel-config.js

Prepare to include https://github.com/avajs/babel-preset-stage-4/pull/13. Document the new `modules: false` option, and load syntax plugins for object rest/spread and async generators.

Stage 4 updates

---

lib/test-worker.js
test/cli.js
test/fixture/require-compiled-helper/dependency.js
test/fixture/require-compiled-helper/package.json
test/fixture/require-compiled-helper/test/_helper.js
test/fixture/require-compiled-helper/test/verify.js

AVA now installs its source map support and precompiler hook *before*
processing the "require" paths. This means that helpers can safely be
added to the "require" configuration and their compiled versions will be
loaded. Fixes #1506.

Load compiled helpers if in the "require" configuration

---

docs/recipes/babel.md

I noticed this behavior whilst assessing the impact of #1664. This seems to be a good workaround.

Document how to configure @babel/register to *not* compile test and helper files

---

profile.js

Read the 'compileEnhancements' option from package.json and guard
against the Babel config helper not returning any config.
See https://github.com/avajs/ava/issues/1556#issuecomment-361962088.

Ensure profile.js skips test file compilation like regular runs

---

docs/recipes/babel.md
docs/support-statement.md

Add links to french translation:
* babel.md
* support-statement.md
Note: The doc is up to date for 1.0.0-beta.1

Docs: Add link to french translation (babel & support-statement)

---

lib/assert.js
lib/runner.js
lib/test.js
readme.md
test/assert.js
test/test.js

* Assertions are now bound. Fixes #1592.
* Assertions are now skipped by calling `.skip()` at the end, e.g. `t.fail.skip()`. This is consistent with the test interface, where `skip()` can only be used at the end of the chain.
* The private `t._test` value has been removed. Instead a WeakMap is used internally to look up the corresponding Test instance given an ExecutionContext.
* Fix `t.snapshot.skip()`. Ensure subsequent `t.snapshot()` calls compare the correct snapshot. Forbid snapshots from being skipped while updating them. Fixes #1425.

Bound execution context and changed skip

---

docs/recipes/babel.md

Following discussion of #1309, this PR attempts to clarify the documentation to avoid confusion when first setting up AVA with ESNext source files.

Make source compilation clearer

---

readme.md

Fixes #1579.
Heads up @kugtong33.

Document context support in before & after hooks

---

api.js
test/api.js
test/fixture/fail-fast/without-error/a.js
test/fixture/fail-fast/without-error/b.js

The interrupt call wasn't properly guarded and ran whenever a test result was received, rather than when a test failed.

Fix --fail-fast accidentally interrupting test files

---

index.d.ts
index.js.flow
lib/assert.js
readme.md
test/assert.js
test/test.js

Fixes #1720 
Remove `ifError()` method , remove `t.ifError` documentation on readme and update affected tests

Remove the `t.ifError` assert method

---

.github/issue_template.md
contributing.md
readme.md

As Gitter's development seems to have slowed since their acquisition by GitLab we're moving our chat to Spectrum. It's a new product so still rough around the edges, but it's way more than a chat room which we think will be quite useful for the AVA community.
Come join us at https://spectrum.chat/ava!

Move to Spectrum

---

readme.md

Added instructions for running `ava --init` with `npx` when installing ava locally and at least `npm@0.5.2`

Update readme.md to include running init with npx

---

docs/recipes/precompiling-with-webpack.md

Progress #1662
The files weren't too different so this could be a non-issue. I did see an outdated link and polished that up.

Updating recipes #2

---

docs/recipes/debugging-with-webstorm.md
lib/cli.js
package-lock.json
package.json
readme.md

Fixes #1737.
This removes the `--init` flag and associated dependency on `ava-init` in favor of recommending `npx ava-init`. See the linked issue for reasoning.
Happy to update this to `@ava/init` if the package is republished there. 😊
(Does yarn have an npx equivalent? Maybe it doesn't matter, since Yarn users presumably also have npx installed.)

Replace --init flag with npx recommendation

---

bench/run.js

`bench/run.js` did not import `bluebird` but used `Promise.each()` which resulted in an error.

Fix Missing Import In bench/run.js

---

readme.md

This pull request fixes #1750, a need for better documenting of ignore patterns . Before creating this issue user vjpr was unable to find documention on this issue with keyword searches. I added a simple explanation using the words 'ignore' and 'exclude'  so that users unsure how to ignore tests will also be more likely to find my explanation in keyword searches. 
I also changed not-this-file.js to exclude-this-file.js to provide a clearer example to users reading the documentation.

Document how to exclude a directory

---

index.d.ts
index.js.flow

I believe it is valuable to have inline docs here. If I type `t.` in my editor I like to be able to scroll through all the assertion options and see what they do.

Add inline docs to Assertions interface in type definitions

---

readme.md

Got this error:
```sh
✖ The 'source' option has been renamed. Use 'sources' instead.
```

Update readme.md source => sources

---

lib/babel-pipeline.js
lib/worker/precompiler-hook.js
test/api.js

See commits. The first one is a follow-up to #1798, the second fixes #1804.

Handle Babel not returning source maps

---

package-lock.json
package.json

Since ebb3948, the del module is referenced not only in test code. Hence del needs to be a prod dependency.
Fixes #1824

Fix missing `del` dependency

---

lib/babel-pipeline.js
lib/reporters/improper-usage-messages.js
test/cli.js
test/helper/report.js
test/reporters/mini.js
test/reporters/mini.regular.log
test/reporters/verbose.js
test/reporters/verbose.regular.log

Prevents the documentation links that AVA returns from going out of date.
Closes #1757.

Make links point to specific git tag

---

lib/snapshot-manager.js

Rename `newLength` to `checkPosition` to make the function clearer.
At the end of the loop `checkPosition` points to the last index that
does not contain a line ending, so add one to include it.
Fixes #1848

Fix snapshot report merging.

---

index.d.ts
index.js.flow
lib/worker/main.js

Fixes #1862. The `test()` method is already available as the default export.

Remove test export

---

index.d.ts
index.js.flow
lib/assert.js
readme.md
test/assert.js

See discussion in #1794. It feels out of place compared to promises and requires many overloads in the type definitions.

Remove observable support in t.throws() and t.notThrows()

---

lib/load-config.js
package-lock.json
package.json

This ensures user settings don't leak into our use of esm.

Upgrade esm and use force option

---

bench/compare.js
docs/recipes/when-to-use-plan.md
lib/ava-files.js
lib/serialize-error.js
lib/watcher.js
lib/worker/dependency-tracker.js
lib/worker/subprocess.js
test/api.js
test/fixture/debug-arg.js
test/fixture/inspect-arg.js
test/integration/assorted.js
test/integration/concurrency.js
test/integration/watcher.js
test/watcher.js

Some things XO wouldn't catch.

Modernize some code

---

index.js.flow

This allows Flow promise types to be compatible with what AVA is expecting
https://github.com/facebook/flow/blob/c88262be2be0b94b04bfaaf5e52570856d0b87e3/lib/core.js#L589-L597
These should no longer require extra typing:
```js
await t.throws(() => promise);
await t.throws(promise);
```
PS: This PR was made by @jamiebuilds from my computer. "HI!" – Jamie

Copy flow's promise then() interface into PromiseLike

---

docs/recipes/flow.md
docs/recipes/when-to-use-plan.md
index.d.ts
index.js.flow
lib/assert.js
readme.md
test/assert.js
test/flow-types/regression-1148.js.flow
test/test.js

See #1794.
---
`t.throws()` and `t.notThrows()` no longer take async functions or promises. Instead, use `await t.throwsAsync()` and `await t.notThrowsAsync()`. The async assertions fail if the function throws synchronously.
Updated tests, documentation and type definitions.

Move promise-handling code to t.throwsAsync and t.notThrowsAsync

---

docs/recipes/endpoint-testing-with-mongoose.md

fix small typo in setup list mongod-memory-server -> mongodb-memory-server
copied and tried to install it, which of cause failed, so might safe others ;-)

Fix typo in endpoint-testing-with-mongoose

---

lib/fork.js
lib/worker/fake-tty.js
test/fixture/node-assertions/assert-failure.js
test/fixture/tty/color-disabled.js
test/fixture/tty/color-enabled.js
test/fixture/tty/get-color-depth-missing.js
test/fixture/tty/is-not-tty.js
test/fixture/tty/is-tty.js
test/helper/cli.js
test/helper/simulate-tty.js
test/integration/node-assertions.js
test/integration/tty.js

The AssertionError constructor in Node 10 depends on the TTY
interface. More specifically, if isTTY is true on stdout then
getColorDepth() must also be available. Ava provides a shim for
isTTY in the test workers but does not provide a getColorDepth()
implementation. This leads to unexpected failures when code under
test is using Node's built-in assert module.

Provide getColorDepth() shim for fake TTYs

---

docs/recipes/babel.md

If someone were to blindly copy & paste the example (as I did), things go bad when node spawns too many processes trying to compile files under `node_modules`.

Ignore node_modules/* in example

---

package-lock.json
package.json
test/integration/stack-traces.js
test/reporters/mini.regular.log
test/reporters/tap.failfast.log
test/reporters/tap.failfast2.log
test/reporters/tap.regular.log
test/reporters/verbose.regular.log

I think the fixes from https://github.com/evanw/node-source-map-support/pull/220 are causing some test failures on our end. This should fix it.

Bump source-map-support and update tests

---

readme.md

Configuration section of README says "All of the CLI options can be configured", and goes on to provide a detailed spec which doesn't include the `verbose` option

Include `verbose` option in Configuration section of README

---

lib/babel-pipeline.js
test/fixture/babel/with-explicit-syntax-plugins/async-generators/package.json
test/fixture/babel/with-explicit-syntax-plugins/async-generators/test.js
test/fixture/babel/with-explicit-syntax-plugins/object-rest-spread/package.json
test/fixture/babel/with-explicit-syntax-plugins/object-rest-spread/test.js
test/fixture/babel/with-explicit-syntax-plugins/optional-catch-binding/package.json
test/fixture/babel/with-explicit-syntax-plugins/optional-catch-binding/test.js
test/integration/babel.js

AVA needs to add syntax plugins for stage-4 features, however it
shouldn't do so if the user has already specified them. This fixes the
detection of existing plugins by also comparing a `default` export of
the plugin package.
Fixes #1828.

Fix detection of existing syntax plugins

---

readme.md

Fixes #1929 
Adds documentation to main Readme file considering the `--reset-cache` CLI command

adds --reset-cache flag documentation to mean readme

---

profile.js

Fixes #1819
When we need to debug our code, we launch ava not from cli, but using profile.js.
In this file the `precompileFile` was hardcoded, so files were always transpiled through babel, which was the issue with projects on typescript, where we do not need babel at all.
I took code api.js to choose when to use babelPipeline and when not.
There is some code duplication problem now between `api.js` and `profile.js`, which can not be easily refactored.

Fix profile.js was not able to work without babel

---

lib/assert.js
test/assert.js

This is for #1932.
Here's the overview of what the lines do:
- Checks if the `fn` argument to `t.throws()` returns a promise and adds a no-op `.catch()` handler to the return value prevent ava from logging an unhandled rejection
- If it returns a promise, calls `fail()` with the message "`t.throws()` cannot be called with an asynchronous function. Use `t.throwsAsync()` instead"
- Wraps all this in a try-catch statement in order to add the `.catch()` handler in the conditional
I used the test case from #1931:
```
import test from 'ava';
test('test', async (t) => {
await t.throws(async () => {
throw new Error();
});
});
```
The output running npm test is:
```
15: test('test', async (t) => {     
16:     await t.throws(async () => {
17:         throw new Error();      
`t.throws()` cannot be …
```

Providing useful feedback when using t.throws() with async functions

---

readme.md

I created this PR because:
> This documentation covers the 1.0 beta releases, **which use Babel 7.**

Change babel-register to @babel/register

---

lib/babel-pipeline.js
test/api.js
test/fixture/babel-config/.alt-babelrc
test/fixture/babel-config/babel.config.js
test/fixture/babel-config/package.json
test/fixture/babel-config/test.js

This adds support for `babel.config.js` files but does not address the documentation. It'll be good to get at least a release out so people can test.
See #1816.
PR against #1954, will rebase before merging.

Support babel.config.js

---

docs/recipes/puppeteer.md
readme.md

Added recipe for using AVA with Puppeteer for testing web apps.
Work in progress, recipe may be incomplete or buggy. I think it's worth adding a few pictures and more examples. If you have an idea for enhancing this recipe, write it in the comments.
Fixes #1799

Add recipe for AVA & Puppeteer

---

lib/snapshot-manager.js

I reckon this fixes a regression introduced in https://github.com/avajs/ava/pull/1852.

Insert a trailing newline when appending new snapshot entries

---

lib/runner.js
lib/snapshot-manager.js
test/assert.js
test/integration/snapshots.js
test/test.js

* Use the filename of the source file to build the snapshot filename
* Put the relative path of the actual source file in the Markdown snapshot
This is great for TypeScript projects where AVA is applied to pre-build files. The snapshots will be named `file.ts.snap`, and the relative path will be correct, rather than pointing at the output directory.
---
This is a breaking change, since AVA will now write new snapshot files, without removing the previous ones. It may not catch bugs introduced at the same time as the project is updated to the new AVA version.

Use source-mapped file to build snapshots

---

lib/beautify-stack.js
lib/serialize-error.js
test/serialize-error.js

`esm` changes error stacks in a way that AVA is not expecting. This adds a few workarounds, though admittedly all the packages we're using and workarounds we're applying are making a bit of a mess.
See https://github.com/standard-things/esm/wiki/improved-errors for `esm`'s behavior.

Handle esm's error "improvements"

---

docs/recipes/typescript.md
index.d.ts
index.js.flow
lib/runner.js
readme.md
test/runner.js

Previously, AVA would pass the empty string. By passing an undefined value, the title function can use argument defaults which is more natural.
---
This is a breaking change for users who were concatenating `title`, under the assumption it was an empty string.

Pass an undefined title argument to macro-title functions

---

docs/recipes/typescript.md
index.d.ts
test/ts-types/context.ts
test/ts-types/macros.ts

This is an attempt at inferring the types of the additional arguments when you use macros.
```typescript
const hasLength: Macro<[string, number]> = (t, expected, length) => {
t.is(expected.length, length);
};
test('bar has length 3', hasLength, 'bar', 3);
const hasCodePoints: Macro<[string, number]> = (t, expected, length) => {
t.is(Array.from(expected).length, length);
};
test('bar has length 3', [hasLength, hasCodePoints], 'bar', 3);
```
See `test/ts-types/macro.ts` for more examples.
This all works quite well as long as you provide the correct arguments. However, the feedback when you don't is atrocious. Due to the way we overload the `test()` function TypeScript assumes you're trying to use `test(macro, ...args)` if it can't match `test('title', macro, ...args)`, which means it's …

Type additional arguments used by macros

---

package.json
readme.md

Something I've been mulling over for a while. @sindresorhus what do you think?

Update the tagline and readme intro

---

docs/01-writing-tests.md
docs/02-execution-context.md
docs/03-assertions.md
docs/04-snapshot-testing.md
docs/05-command-line.md
docs/06-configuration.md
docs/07-test-timeouts.md
docs/08-common-pitfalls.md

Fix links to French translation of docs

---

docs/01-writing-tests.md
index.d.ts
index.js.flow
lib/create-chain.js
lib/runner.js
test/api.js
test/fixture/meta.js

This creates `test.filePath` which exposes the filename of the test
being run by ava.
Fixes #1976

Expose test file path within test process.

---

lib/serialize-error.js
test/serialize-error.js

1. Fixes #1995
2. Add `lines[index].startsWith('    at')` for fixing tests from `test/reports/*.js`
3. Change `skips esm enhancement lines when finding the summary` test in `test/serialize-error.js` for checking my changes
4. Firstly, I change `serialize standard props` test in in `test/serialize-error.js` 
from:
`t.is(serializedError.summary, 'Error: Hello');`
to:
`t.is(serializedError.summary, error.stack)`;
But after adding fix for `test/reports/*.js` I return it to initial 
`t.is(serializedError.summary, 'Error: Hello');` and it also pass

Change serialization of Error summary due to #1995

---

docs/02-execution-context.md
docs/07-test-timeouts.md
index.d.ts
index.js.flow
lib/test.js
test/test.js

Fixes #1565 
As suggested in the issue, the timeout is refreshed whenever an assertion is made.
I'm not sure if the typescript or flow definitions need to be updated.

Add `t.timeout()`

---

docs/recipes/debugging-with-vscode.md

Fixes #2023
This PR changes the lines containing the deprecated variable into the new equivalent one.
In "Debugging tests with Visual Studio Code" recipe the {workspaceRoot} variable has been deprecated since version 1.17 in favor of {workspaceFolder}.

[Docs] Remove deprecated variable from VS Code debug recipe

---

api.js
lib/cli.js
lib/reporters/mini.js
lib/reporters/verbose.js
lib/run-status.js
test/integration/assorted.js
test/reporters/verbose.timeoutinmultiplefiles.log
test/reporters/verbose.timeoutinsinglefile.log

print pending tests on interrupt

---

lib/ava-files.js
test/ava-files.js

This fixes #1511 by recognizing snapshot (`.snap`) files as source files.
Note that I didn't add an integration test as requested in https://github.com/avajs/ava/pull/1751#pullrequestreview-108522952 since the two assertions I added to the `ava-files.js` unit tests should be enough. If you still think we need an integration test for this, let me know and I'll add one.
// cc @novemberborn

Delete snapshots files after running tests

---

package.json

It's not needed as TypeScript infers the file just like Node.js does for `index.js`.

Remove the moot `typings` field in package.json

---

lib/worker/subprocess.js
package-lock.json
package.json

This PR updates ava's `esm` detection to use a simplified symbol value.

Update esm package detection

---

lib/test.js

Test code should be able to stuck the global clearTimeout() without breaking AVA.
This fixes a regression from #2015 (v1.2.0).

Fix unbound reference to clearTimeout

---

readme.md

This purposefully splits the two ways of writing and don't use the schwa (inverted e) in the alternative non-IPA writing. The reason I'm proposing this change is because I had an employee ask me about "why is there something after that second `/`? Do I have to say ava twice?
In our case downloading and listening to the file made it clear, but I think writing it out in IPA and writing it out without any IPA-characters makes it unambiguous and removes the need to download the audio file (which is not very accessible).

Split the two ways of writing the pronunciation

---

lib/assert.js
test/assert.js

A tiny bug with a tiny fix. Title describes it all.

Bug fix: t.throws() does not fail when expected code is a number

---

test/fixture/report/regular/unhandled-rejection.js
test/helper/report.js
test/reporters/mini.regular.log
test/reporters/tap.js
test/reporters/tap.regular.log
test/reporters/verbose.regular.log

This should fix failures in https://github.com/nodejs/citgm.

Tweak reporter integration tests so they pass on Node.js 12-pre

---

index.d.ts
test/ts-types/macros.ts

I have noticed that with the types before the proposed change (current types), the following type checks (but it should not). I'm not sure if version of typescript matters here or not, but I'm using 3.3.4000. However, if the title is removed from the test definition, it will fail as it should and even with proper error.
```ts
const hasLength: Macro<[string, number]> = (t, input, expected) => {
t.is(input.length, expected);
};
test('bar has length 3', [hasLength], 2, 3); // should fail
//                                    ^ Wrong type
test([hasLength], 2, 3);
//                ^ error TS2345: Argument of type '2' is not assignable to parameter of type 'string'.
```
----
The change removes all of the crafty and clever type stuff in favor of simpler solution. Additionally, this change …

Simplify macro types

---

lib/api.js
lib/cli.js
test/api.js
test/helper/report.js

Originally the goal may have been for this to be accessible
programmatically, but it's unclear whether we'd ever end up supporting
that. For now moving it into the lib/ directory better communicates it's
internal.

Move api.js into lib/

---

lib/api.js
lib/assert.js
lib/runner.js
lib/snapshot-manager.js
lib/worker/subprocess.js
test/integration/snapshots.js

Fail snapshot assertions in CI if snapshot is missing

---

lib/assert.js
test/assert.js

Ensure the assertion message is a string

---

docs/recipes/typescript.md

The getting started example contains a minor defect.  Ava requires a label, but the example given does not have one.
```
test(async t => {
t.is(await fn(), 'foo');
});
```
Result:
```
$ npx ava ./src/test/testset.ts
Uncaught exception in src\test\testset.ts
(censored)\src\test\testset.ts:12
11:
12: test(async t => {
13:   t.is(await fn(), 'foo');
TypeError: Tests must have a title
Object.<anonymous> (src/test/testset.ts:12:5)
Module.m._compile (node_modules/ts-node/src/index.ts:439:23)
Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:442:12)
```
Proposed replacement:
```
test('receive foo asynchronously', async t => {
t.is(await fn(), 'foo');
});
```

Fix sample test in TypeScript recipe

---

docs/recipes/babel.md

When using a separate file for `@babel/register` a relative path must be required.

Update invalid require path in babel recipe

---

docs/recipes/flow.md

@novemberborn recommended in #2100 that having async tests as leading tests may be undesirable, and requested a removal here

Convert test in flow.md recipe from async to sync

---

index.d.ts
test/ts-types/macros.ts

This fixes a copy/paste mistake in the TS definition preventing us from using the `skip` method with macros and without a title.

Fix the `SkipInterface` in the TypeScript definition

---

docs/06-configuration.md
lib/concordance-options.js

When printing objects or exceptions, Ava restricts the depth of the printed objects to 3 levels. Some libraries that like to throw exceptions with deeply nested data in them (e.g. Axios) would benefit from increasing the printing depth when debugging failing tests, but unfortunately this depth is hardcoded in Ava and it's not possible to change it by the user.
I would propose instead to tie this depth to [`util.inspect.defaultOptions.depth`](https://nodejs.org/api/util.html#util_util_inspect_defaultoptions), which is a setting that NodeJS uses to control the depth of printing for `console.log()` and similar. Most NodeJS developers who have had to debug deeply nested objects by printing them with `console.log()` are already familiar with this setting, so it would come natural to use the …

Make the object printing depth configurable

---

lib/reporters/tap.js
test/reporters/tap.regular.log

Fix #2118 I think it could be better to include full stack trace

Include all (beautified) stack trace lines in TAP reporter output

---

lib/reporters/tap.js
test/reporters/tap.regular.log

The `t.log` outputs were not included in the TAP reporter output (`--tap`) unless they failed:
```
TAP version 13
console.log in hook
console.log inside
ok 1 - suite › api › events › [C806010, monitoring, validation, xxx] [eventsApi ea2] Get Events
* t.log inside
* t.log inside2
1..1
```

Include logs from successful hooks in TAP output

---

lib/assert.js
lib/serialize-error.js
lib/test.js

Fixes #1399.
My idea was to always try to pass a new `Error` object in the AssertionError instead of a `stack` string. It might be a bit more memory inefficient, but it would allow for a more consistent behavior overall.
I then expose the `savedError`'s stack when `serializeError` is called.
One thing that I'm not too sure about is the `Error.stackTraceLimit` of the new Error object. I'm not sure if it takes effect when calling `new Error()` or at the point of getting the stack from the `savedError`. I would assume the first case applies. If that's the case, I can do the `Error.stackTraceLimit` "dance" before creating the new Error. 
The changes need to be unit tested and I will do that as well in this PR, but I first wanted someone to take a quick look over the changes and let me know if …

Store an error object in AssertionError rather than a stack trace

---

package.json
readme.md

Amends #2098 and entirely removes Flow references, as support currently does not exist and retained information is misleading.

Remove Flow references

---

readme.md

Line 125 of readme.md starts with
'We aim support all finished syntax proposals,'
Added the word 'to' after 'aim'.
This is my first ever pull request, I hope I am doing this correctly.

Fix grammar in readme

---

readme.md

vscode recipe link is missing from readme
restore it

docs(readme): restore vscode debug recipe

---

test/helper/report.js

To ensure tests pass under Node.js 12.6.

Disable deprecation warnings in reporter tests

---

index.d.ts

Previously, the Context was typed as an empty object. This suddenly started giving problems when typing `t.try()` (https://github.com/avajs/ava/pull/1947#issuecomment-498038318). Setting it to `unknown` seems reasonable.
This may break some code, but I'm not sure how you'd use context without typing it, and IIRC there was a non-major TypeScript change that led to similar breakage regarding the `{}` type. It seems like the kind of breakage that TypeScript users are used to, so we shouldn't need a major bump to release this. @sindresorhus?

Change default Context type to unknown

---

lib/api.js

Fixes #2163 
Now the error is:
```
➜  test npx ava test.js --verbose
✖ Couldn't find any files to test
✖ Internal error
Error: ENOENT: no such file or directory, mkdir '/Users/yovasx2/test/node_modules/.cache/ava'
Error: ENOENT: no such file or directory, mkdir '/Users/yovasx2/test/node_modules/.cache/ava'
at Object.mkdirSync (fs.js:752:3)
at AsyncFunction.module.exports.sync (/Users/yovasx2/test/node_modules/make-dir/index.js:108:6)
at Api._setupPrecompiler (/Users/yovasx2/test/node_modules/ava/lib/api.js:278:11)
at Api.run (/Users/yovasx2/test/node_modules/ava/lib/api.js:111:35)
at Object.exports.run (/Users/yovasx2/test/node_modules/ava/lib/cli.js:283:31)
at Object.<anonymous> (/Users/yovasx2/test/node_modules/ava/cli.js:10:23)
at Module._compile (internal/modules/cjs/loader.js:701:30) …
```

Print internal errors when precompiler setup or globbing fails

---

lib/worker/fake-tty.js
test/fixture/tty/callbacks.js
test/integration/tty.js

See the release notes for `tty`: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.7.0:
We should really check if we can just use the built-in modules. I'm not sure why we're faking TTY anymore! 😄

Update fake-tty for changes in Node.js 12.7.0

---

lib/watcher.js

See https://github.com/avajs/ava/issues/2205#issuecomment-520237673.

Watcher: Only track test files has having exclusive tests if at least one test was selected

---

lib/api.js

use `includes()` to check for existence instead of `indexOf()`

Minor code refactor

---

docs/recipes/endpoint-testing.md

Some people may want to use a more familiar client to them like fetch, got and etc when endpoint testing. Let's explain how to do that!

Explain how to use custom HTTP clients when endpoint testing

---

docs/recipes/typescript.md

`ts-node` has issues with usage of the path aliases. The only solution, that I've found so far is to use the [tsconfig-paths](https://github.com/dividab/tsconfig-paths#readme), which is dedicated for address this problem. So decided to add another typescript recipe

Document module path mapping in TypeScript recipe

---

docs/recipes/babel.md
lib/api.js
lib/babel-pipeline.js
lib/cli.js
lib/extensions.js
lib/load-config.js
lib/reporters/mini.js
lib/reporters/verbose.js
profile.js
test/integration/babel.js
test/integration/config.js
test/integration/environment-variables.js
test/integration/extensions.js
test/integration/globs.js

This lays the groundwork for a future AVA release which will *not* run Babel out of the box. This also explicitly couples the compiled enhancements (power-assert, `t.throws()` error handling) with the Babel pipeline.
The implementation is a bit muddled with lots of checks for the experiment, but it gets the ball rolling. The next step is to create a new `@ava/babel` package which will implement both the legacy Babel pipeline *and* the new one.
Then, in a future breaking release we'll make `@ava/babel` an optional peer dependency, and require AVA's `babel` configuration to be set before files are processed by the Babel pipeline.
We'll build on top of this to enable source file compilation and find a shared interface we can use to do TypeScript compilation.

Experimentally disable Babel out of the box

---

test/integration/compilation.js

The error message has changed in a recent Node.js 12 release.

Loosen matches for import syntax errors

---

docs/01-writing-tests.md

Fixed typo, now reads `Similarly test.afterEach() registers a hook to be run...`. Fixes #2264 .

Fix typo in the docs for writing tests

---

lib/cli.js

Missed this one in #2313. It's still kinda wrong, see https://github.com/avajs/ava/issues/1701 but that's for another time.

Correctly set Chalk level based on --color CLI boolean flag

---

docs/01-writing-tests.md
docs/02-execution-context.md
docs/03-assertions.md
docs/04-snapshot-testing.md
docs/06-configuration.md
docs/08-common-pitfalls.md
docs/recipes/browser-testing.md
docs/recipes/endpoint-testing-with-mongoose.md
docs/recipes/es-modules.md
docs/recipes/flow.md
docs/recipes/isolated-mongodb-integration-tests.md
docs/recipes/passing-arguments-to-your-test-files.md
docs/recipes/puppeteer.md
docs/recipes/react.md
docs/recipes/vue.md
readme.md

Out of the box, ESM syntax will only work in Node.js 13, so having that
as the default example is misleading.
Leave it for the TypeScript recipe since TypeScript doesn't work out of
the box anyway. Leave the config example, which will be updated when we
update the config formats for ESM.

Use CJS syntax in documentation

---

test/test-try-commit.js

This is the one test that is still flaky on Windows.

Tweak timeout value in t.try() test

---

test/fixture/fail-fast/multiple-files/passes-slow.js

Hopefully this removes more flakiness from Windows tests.

Increase timeout in fail-fast interrupt test

---

docs/07-test-timeouts.md
lib/cli.js

Now that our timeout implementation is pretty good, we can set a default timeout.
10 seconds seems reasonable to me.
We exit the worker process after the timeout is reached, which should help with issues like #2310.
Fixes #2310.

Set a default timeout of 10 seconds

---

docs/03-assertions.md

I have switched to this in my own docs as many users were confused about the brackets `[message]` and thought it meant an array. Question mark is already commonly used to indicate optional arguments, for example, in TypeScript.

Use question mark to indicate optional argument in docs

---

lib/assert.js

a fix to `t.assert()` implementation without power-assert.
closes #2354

Ensure t.assert() counts as a passed assertion

---

docs/recipes/debugging-with-vscode.md

`configurations` is an array, not an object.

Fix VSCode debugging instructions

---

package-lock.json
package.json
test/api.js
test/fixture/fail-fast/multiple-files/passes-slow.js

Listen for the peer-failure notification before resuming tests. Then
verify the test execution was interrupted.

Fix fail-fast interrupt test

---

docs/06-configuration.md
docs/recipes/typescript.md
eslint-plugin-helper.js
lib/api.js
lib/cli.js
lib/extensions.js
lib/provider-manager.js
lib/worker/subprocess.js
test/api.js
test/helper/report.js

This adds very rudimentary support for loading TypeScript test files, as discussed in https://github.com/avajs/ava/issues/1109#issuecomment-557805037.
Leaving this as a draft until `@ava/typescript` ships. See https://github.com/avajs/typescript/pull/1.

Rudimentary support for loading TypeScript test files

---

lib/test.js

Improve error message when `test.cb()` is used with promises

---

lib/test.js
test/helper/ava-test.js
test/test-try-commit.js

@qlonik I've been using `t.try()` for a while now. This is the only thing I can think of changing. Will try and get documentation done too.

t.try() title improvements

---

lib/esm-probe.mjs
lib/worker/subprocess.js

Replace `lib/esm-probe.mjs` file by a dataURL, 
~and we don't care about the `import` result, we don't have to wait~
Cache the detect result, so we don't have to wait for a microtask everytime
@arlac77

Improve ESM support detect

---

docs/03-assertions.md
docs/06-configuration.md
lib/load-config.js
lib/test.js
test/helper/ava-test.js
test/test-try-commit.js
test/try-snapshot.js

This removes the tryAssertion experiment.

Ship t.try() without requiring opt-in

---

docs/recipes/debugging-with-chrome-devtools.md
lib/cli.js
lib/worker/subprocess.js

Fixes #2406
Previously AVA in debug mode was listening only on hardcoded '127.0.0.1' (loopback) interface.
Now, it defaults to loopback, with an override command line option: "--host".
Example usage:
`node ava debug --host 0.0.0.0 --break "${relativeFile}"`

Add debug --host option

---

docs/recipes/endpoint-testing.md

There is a small typo in docs/recipes/endpoint-testing.md.
Should read `preferably` rather than `preferrably`.

Fix typo in endpoint testing recipe

---

docs/02-execution-context.md
index.d.ts
lib/context-ref.js
lib/runner.js
lib/test.js
test-tap/hooks.js

Instead of introducing the a new hook (PR #2427) the property `t.passed` is passed to the hook `afterEach.always`.
Fixes https://github.com/avajs/ava/issues/840.

Add t.passed to execution contexts

---

.github/workflows/ci.yml
docs/recipes/typescript.md
package.json

To avoid accidentally breaking compatibility with older TypeScript versions, test with each supported version.

Test our type definitions with multiple TS versions

---

lib/reporters/mini.js

As title says, I solved the issue with the mini reporter + watch mode:
It turned out, the terminal spinner package, ora [doesn't pipes through the stdin by default][1], which was a [breaking change in its 4.0.0 relase][2]. I suppose during one of the dependency update the effect of this change was overlooked and caused the issue.
I ran the test locally on Linux, everything was green.
Please review and merge it accordingly!
Fixes #2458.
[1]: https://github.com/sindresorhus/ora#discardstdin
[2]: https://github.com/sindresorhus/ora/releases/tag/v4.0.0

Fix watch mode with mini reporter

---

lib/assert.js
lib/concordance-options.js
test-tap/fixture/report/regular/nested-objects.js
test-tap/reporters/mini.regular.v10.log
test-tap/reporters/mini.regular.v12.log
test-tap/reporters/mini.regular.v13.log
test-tap/reporters/mini.regular.v14.log
test-tap/reporters/tap.regular.v10.log
test-tap/reporters/tap.regular.v12.log
test-tap/reporters/tap.regular.v13.log
test-tap/reporters/tap.regular.v14.log
test-tap/reporters/verbose.regular.v10.log
test-tap/reporters/verbose.regular.v12.log
test-tap/reporters/verbose.regular.v13.log
test-tap/reporters/verbose.regular.v14.log

The depth-limit for `t.deepEqual` was always set to 1. Fixed it.
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#1850: Object diffs are not always useful](https://issuehunt.io/repos/26820798/issues/1850)
---
</details>

Use configured depth limit for diffs in assertion failures

---

docs/recipes/endpoint-testing.md

Got library uses `prefixUrl` not `baseUrl`. Also, got errors if path begins with a slash, so replaced `/user` with `user`.

Update endpoint testing recipe to use correct options for got

---

lib/fork.js
package-lock.json
test/test-timeouts/fixtures/custom-message.js
test/test-timeouts/fixtures/invalid-message.js

This reverts commit 51fafed989a1b0b9e384dc4c589f3453082dcde1.
We're seeing intermittent failures, see https://github.com/avajs/ava/issues/2535.

Revert "Use advanced serialization (when available) for test worker communication"

---

test-tap/reporters/mini.regular.v14.log
test-tap/reporters/tap.regular.v14.log
test-tap/reporters/verbose.regular.v14.log

Clearly this isn't ideal but it gets tests passing for now.

Fix reporter logs for Node.js 14

---

docs/recipes/debugging-with-vscode.md
lib/api.js
lib/cli.js
lib/worker/subprocess.js

VS Code has a new debugger which works differently than the old debugger. Some arguments in the launch config were no longer needed or caused issues, and I also added a method using the debug terminal for users more comfortable with that.
Fixes #2542

Detect active inspectors; update VSCode debugging recipe

---

docs/03-assertions.md
lib/assert.js
lib/load-config.js
test-tap/assert.js
test-tap/helper/report.js
test-tap/test.js
test/assertions/fixtures/package.json

Unflag t.like() assertion

---

docs/recipes/es-modules.md

The ES modules example uses the "require()" syntax for the `test.js` file. This changes to use ES Module "import from ..." syntax in `test.js` example.

Use ESM syntax for ESM example

---

lib/cli.js
lib/fork.js
lib/ipc-flow-control.js
lib/worker/ipc.js
test-tap/fixture/report/regular/uncaught-exception.js
test-tap/reporters/mini.regular.v10.log
test-tap/reporters/mini.regular.v12.log
test-tap/reporters/mini.regular.v14.log
test-tap/reporters/tap.regular.v10.log
test-tap/reporters/tap.regular.v12.log
test-tap/reporters/tap.regular.v14.log
test-tap/reporters/verbose.regular.v10.log
test-tap/reporters/verbose.regular.v12.log
test-tap/reporters/verbose.regular.v14.log
test/helpers/exec.js

- Use advanced serialization (when available) for test worker communication
- Buffer IPC sends to avoid crashes
Try #2530 again but now with a fix for the crashes that led to it being reverted in #2536.
See https://github.com/nodejs/node/issues/34797 for what I believe is a reproduction.

Use advanced serialization (when available) for worker communication

---

docs/recipes/react.md

React's enzyme recipe was updated to work with latest react (v16) and enzyme (v2) versions. I made the following assumptions:
- React is already configured in the project, therefore no instructions to add `react`, `react-dom` and `prop-types` packages were added
- Used the [browser testing recipe](https://github.com/avajs/ava/blob/master/docs/recipes/browser-testing.md) structure to guide the user through the configuration process.
Let me know if additional changes are required.
Solves #2522

Update enzyme recipe to work with latest enzyme

---

test-tap/helper/report.js
test-tap/reporters/mini.js
test-tap/reporters/mini.regular.v12.log
test-tap/reporters/mini.regular.v14.log
test-tap/reporters/tap.js
test-tap/reporters/tap.regular.v12.log
test-tap/reporters/tap.regular.v14.log
test-tap/reporters/verbose.js
test-tap/reporters/verbose.regular.v12.log
test-tap/reporters/verbose.regular.v14.log

Fix test failures with Node.js 14.9.

Sanitize timers.js positions in reporter logs

---

docs/02-execution-context.md
lib/test.js
test-tap/test.js

Set the `t.passed` value before teardowns callbacks are executed to enabled logic based on test result.
Fixes #2572

Make `t.passed` usable in tests and teardown functions

---

docs/03-assertions.md
docs/recipes/react.md
lib/assert.js
lib/load-config.js
test-tap/assert.js

Aims to fix https://github.com/avajs/ava/issues/2410

Experimentally disable null expectations for throws assertions

---

lib/plugin-support/shared-workers.js

Each test process using the shared worker will add a listener. There could be more than 10 processes using the worker concurrently. Disable the standard listener limit since the warning it prints is irrelevant.

shared-workers: Don't warn when too many message listeners are added

---

lib/api.js

Avoid potential permission issues if we don't use the cache dir anyway, see <https://github.com/avajs/ava/issues/1128#issuecomment-716745299>.

Only create the cache directory when needed

---

.github/ISSUE_TEMPLATE/config.yml

As far as I can tell the link to https://github.com/avajs/ava/discussions was never showing up because of the missing `about` key.

Fix link to Discussions in issue template

---

docs/recipes/endpoint-testing-with-mongoose.md

`getConnectionString` is deprecated in newer versions, use `getUri` instead

Update endpoint testing with Mongoose recipe

---

docs/06-configuration.md

Closes #2674 
I found the information in the CLI documentation:
https://github.com/avajs/ava/blame/main/docs/05-command-line.md#L28-L29

Document that concurrency can be configured in the config files

---

package-lock.json
package.json

`@ava/typescript` is an optional peer dependency - this should be indicated in `package.json`, otherwise stricter package manages (such as Yarn PnP) throw errors:
> ✖ ava tried to access @ava/typescript, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Add Babel and TypeScript provider packages as optional peer dependencies

---

docs/03-assertions.md
index.d.ts
lib/assert.js
test-tap/assert.js

Apologies for dropping this. I just finished university! 🥳 
Hoping to still contribute to this awesome project. I picked up where [this](https://github.com/avajs/ava/pull/2586/files) left off. I totally understand if this PR is closed, given that I left it hanging for a while, but wanted to give it another go at resolving #2455, since it doesn't look like #2586 is active any longer.

Return booleans indicating whether assertions passed

---

index.d.ts
test-d/assertions-as-type-guards.ts

Update the `deepEqual`, `like`, `false`, `true` and `is` assertions so they can be used as type guards. Fixes #2456.
Change the `deepEqual`, `like` and `is` assertions so the actual and expected parameters can be typed separately. Fixes #2580.

Turn assertions into type guards

---

lib/fork.js

This is old and untested. I don't know if it's still relevant. We could always bring it back.

Remove --preserve-symlink and npm link detection

---

lib/serialize-error.js

This PR is to address https://github.com/avajs/ava/issues/2744. I also removed the try keyword, since if we were removing catch, I didn't see the value of using try - I might have missed something though.

Improve callsite handling

---

.gitignore
docs/01-writing-tests.md
examples/macros/index.js
examples/macros/package.json
examples/macros/readme.md
examples/macros/test.js

This PR adds an `examples` directory with currently one example, being `macros`.
I've copied one macro case from the documentation as you will see. We can add a different one, or add multiple test files even. But maybe, the smaller the example, the easier it is to understand for new people. Open to suggestions here.
If you want to test it out how it will look like if you click the button, use this button which does the same but points to my fork.
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/github/SamVerschueren/ava/tree/stackblitz/examples/macros/examples/macros?file=test.js&terminal=test&view=editor)
These are the properties I added to the URL
- Open `test.js` by default if you click the button
- Run the `test` command by …

Add StackBlitz example for macros

---

lib/globs.js
lib/provider-manager.js
lib/watcher.js
package-lock.json
package.json

This breaks compatibility with @ava/babel@1.

Remove support for the AVA 3.0 provider protocol

---

.xo-config.json
docs/05-command-line.md
examples/matching-titles/package.json
examples/matching-titles/readme.md
examples/matching-titles/test.js
examples/specific-line-numbers/package.json
examples/specific-line-numbers/readme.md
examples/specific-line-numbers/test.js
examples/tap-reporter/package.json
examples/tap-reporter/readme.md
examples/tap-reporter/test.js

I've added 3 examples for the [Command line](https://github.com/avajs/ava/blob/main/docs/05-command-line.md) documentation.
- [Running tests with matching titles](https://stackblitz.com/github/SamVerschueren/ava/tree/stackblitz/examples/command-line/examples/matching-titles?file=test.js&terminal=test&view=editor)
- [Running tests at specific line numbers](https://stackblitz.com/github/SamVerschueren/ava/tree/stackblitz/examples/command-line/examples/specific-line-numbers?file=test.js&terminal=test&view=editor)
- [TAP reporter](https://stackblitz.com/github/SamVerschueren/ava/tree/stackblitz/examples/command-line/examples/tap-reporter?file=test.js&terminal=test&view=editor)
Let me know if you want to move buttons to different places or rename directories or what not. Example of the docs …

Add StackBlitz examples for command line documentation

---

docs/recipes/endpoint-testing.md
examples/endpoint-testing/app.js
examples/endpoint-testing/package.json
examples/endpoint-testing/readme.md
examples/endpoint-testing/test.js

Added an example for the [Endpoint testing](https://github.com/avajs/ava/blob/main/docs/recipes/endpoint-testing.md) recipe.
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/github/SamVerschueren/ava/tree/stackblitz/examples/endpoint-testing/examples/endpoint-testing?file=test.js&terminal=test&view=editor)

Add StackBlitz example endpoint testing

---

docs/07-test-timeouts.md
examples/timeouts/index.js
examples/timeouts/package.json
examples/timeouts/readme.md
examples/timeouts/test.js

You can test the example on my fork by clicking the button
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/github/SamVerschueren/ava/tree/stackblitz/examples/timeout/examples/timeouts?file=test.js&terminal=test&view=editor)
Example is pretty straight forward I think. Let me know if you want something differently.

Add StackBlitz example for test timeouts

---

.xo-config.json
docs/recipes/typescript.md
examples/typescript-basic/package.json
examples/typescript-basic/readme.md
examples/typescript-basic/source/index.ts
examples/typescript-basic/source/test.ts
examples/typescript-basic/tsconfig.json
examples/typescript-context/package.json
examples/typescript-context/readme.md
examples/typescript-context/source/index.ts
examples/typescript-context/source/test.ts
examples/typescript-context/tsconfig.json

I improved the TypeScript support on StackBlitz and added two TypeScript examples.
- [Basic example for AVA with TypeScript](https://stackblitz.com/github/SamVerschueren/ava/tree/stackblitz/examples/typescript/examples/typescript-basic?file=source%2Ftest.ts&terminal=test&view=editor)
- [TypeScript example for typing `t.context`](https://stackblitz.com/github/SamVerschueren/ava/tree/stackblitz/examples/typescript/examples/typescript-context?file=source%2Ftest.ts&terminal=test&view=editor)

Add StackBlitz examples for TypeScript

---

docs/05-command-line.md
docs/06-configuration.md
lib/cli.js

Hi! I'm new to AVA and while I was using it I noticed that subsequent runs didn't seem to finish faster even though I wasn't changing some of my test files. This prompted me to try setting up caching, so I set `"cache": true` in my `package.json` like the docs suggested. However, it didn't seem to make a difference and I couldn't find the specified `node_modules/.cache/ava` directory where the cache is supposed to be. Turns out, [AVA itself doesn't cache files unless used with `@ava/babel`](https://github.com/avajs/ava/issues/2481#issuecomment-622302992). This pull request aims to clarify this, both in the docs and when running `npx ava reset-cache`.
Some notes on the changes I made to the docs:
- I specified that the `cache` option is boolean because some (like I did) might think that it …

Clarify caching

---

docs/recipes/debugging-with-vscode.md

The newer version of VSCode changed the command pallet text. This PR is just updating the README to reflect it. It took me a few seconds to find the command.
Awesome project by the way. I've been able to debug a test that easily before. 🎉

Match name of debug task to current VSCode

---

lib/reporters/default.js
lib/reporters/format-serialized-error.js
package-lock.json
package.json

Concordance-formatted text shouldn't have newlines at the start or end. I'm not sure about power-assert output, but let's assume the same.
An extra newline around TypeScript diagnostic text is fine — this is only a convenience for in-process TypeScript compilation which requires a lot of custom configuration to be a thing.
For the remaining use case, trim() should suffice.

Remove trim-off-newlines

---

lib/reporters/prefix-title.js
test-tap/reporters/prefix-title.js

Remove .test, .spec and test- from filenames, in line with the default glob patterns. Retain elsewhere in the path.
Fixes #2793.

Fix prefix normalization

---

docs/recipes/code-coverage.md
docs/recipes/vue.md
lib/reporters/beautify-stack.js

As discussed in #2842 , this PR replaces mentions of using nyc for code coverage in documentation with c8.

Use c8 for code coverage examples instead of nyc

---

docs/recipes/endpoint-testing-with-mongoose.md

Continue previous bad pr, I really sorry about that. Actually this is the changes that I mean before.
My problem is cannot get mongo uri with your current readme on https://github.com/avajs/ava/blob/main/docs/recipes/endpoint-testing-with-mongoose.md.
After doing some search I found update rules to get mongo uri but no update on readme.
So I made this update to make it clear.
Also if I am mistaken, please don't hesitate to reach me out or just ignore this pr ya. Thanks:).

Update Mongoose recipe

---

docs/06-configuration.md
lib/worker/base.js

* Allow providers to load files even if they're ESM.
* Clarify why we still require().
* Update documentation since module format configuration is no longer experimental.

Final ESM tweaks

---

docs/recipes/typescript.md

Using the nodeArgument `--experimental-specifier-resolution=node` makes it so one you don't have to add the `.js` extension to files when importing for your tests. (Such things are not feasible for people with large typescript workspaces)
This PR just updates the typescript recipe to suggest such a change.

Mention experimental specifier resolution in TypeScript recipe

---

lib/code-excerpt.js
package-lock.json
package.json

It's tiny, but still superfluous for a single point of use.

Remove dependency on `equal-length`

---

docs/recipes/typescript.md

https://github.com/avajs/ava/issues/2945
Fix according to this [comment](https://github.com/avajs/ava/issues/2945#issuecomment-1013024157)
> Nice find, that documentation is outdated. The feature is no longer experimental in AVA 4 so this needs to be removed:
> 
> ```
>     "nonSemVerExperiments": {
>       "configurableModuleFormat": true
>     },
> ```

Remove outdated AVA 3 config from TypeScript recipe

---

docs/01-writing-tests.md

This has been removed in AVA 4.

Remove reference to enhanced assertion messages

---

lib/cli.js

Explicitly configure ava --version value

---

docs/01-writing-tests.md
docs/02-execution-context.md
docs/03-assertions.md
docs/06-configuration.md
docs/08-common-pitfalls.md
docs/recipes/browser-testing.md
docs/recipes/endpoint-testing-with-mongoose.md
docs/recipes/endpoint-testing.md
docs/recipes/isolated-mongodb-integration-tests.md
docs/recipes/passing-arguments-to-your-test-files.md
docs/recipes/puppeteer.md
docs/recipes/react.md
docs/recipes/testing-with-selenium-webdriverjs.md
docs/recipes/vue.md
docs/recipes/when-to-use-plan.md

I'm trying AVA for the first time and this appears to be the case as of 4.0.

Update examples in docs to use ES Modules

---

docs/05-command-line.md
lib/cli.js

* Document that line numbers are one-based.
* Mention the validity of line number ranges and multiple comma-separated line number filters.
* Update docs/05-command-line.md to match current output of `ava --help`.

Better explain the syntax and semantics of CLI pattern arguments

---

test-d/deep-equal.ts
types/assertions.d.ts

Loosen type constraints for deepEqual assertion

---

plugin.d.ts
test-d/plugin.ts
test-d/teardown.ts
types/test-fn.d.ts

- Explicitly type t.teardown() functions to return a promise
- Fix typing of plugin teardown. The returned method always returns Promise<void>.
The teardown functions may or may not return a promise. Support both to help with the @typescript-eslint/no-misused-promises ESLint rule.

Improve typing of teardown methods

---

docs/06-configuration.md
docs/recipes/splitting-tests-ci.md
lib/cli.js

Closes #2994 
This PR adds an option `utilizeParallelBuilds` to enable/disable parallel builds. By default, the value of `utilizeParallelBuilds` is true. Setting it to false will disable automatic parallel builds in CI.
For testing purposes I made a GitHub [repo](https://github.com/il3ven/ava-playground) and ran test cases in CI using the [branch](https://github.com/il3ven/ava/tree/parallelBuilds) of this PR.
- With `utilizeParallelBuilds` set to [undefined](https://github.com/il3ven/ava-playground/blob/6a1ec4505a53d0d8bd8fadc3014b6a302279a77d/ava.config.js). We can see test cases being executed in parallel. 
Ref: https://github.com/il3ven/ava-playground/runs/5831541253 (Check npx ava)
- With `utilizeParallelBuilds` set to [false](https://github.com/il3ven/ava-playground/blob/b666d136c106f …

Allow parallel builds to be disabled

---

docs/recipes/shared-workers.md

See https://github.com/avajs/ava/pull/3006 for context.

Document how to load worker multiple times

---

docs/03-assertions.md
lib/assert.js
test-tap/assert.js
types/assertions.d.ts

Fixes #2978 
As per the issue #2978, I have added support for function in `throws`/`throwsAsync` assertion. I have also updated the docs regarding the same. I couldn't find any tests to be updated so I have left them.
How to use?
```js
await t.throwsAsync(async () => {
throw new TypeError('🦄');
}, {
message: message => ['🦄', '🐴'].includes(message)
});
```
Note: This is my first PR in ava so I may have missed something. Please let me know. I will fix it. For example, I am not sure about the [assertion message](https://github.com/il3ven/ava/blob/cbb8d584b358ddbf55824d935c1a151d9c67ba1a/lib/assert.js#L238-L249) to show in case of failure.

Support message testing function in `throws` & `throwsAsync` assertions

---

lib/reporters/default.js
lib/run-status.js
test-tap/reporters/default.timeoutinmultiplefiles.v12.log
test-tap/reporters/default.timeoutinmultiplefiles.v14.log
test-tap/reporters/default.timeoutinmultiplefiles.v16.log
test-tap/reporters/default.timeoutinmultiplefiles.v17.log
test-tap/reporters/default.timeoutinsinglefile.v12.log
test-tap/reporters/default.timeoutinsinglefile.v14.log
test-tap/reporters/default.timeoutinsinglefile.v16.log
test-tap/reporters/default.timeoutinsinglefile.v17.log
test-tap/reporters/default.timeoutwithmatch.v12.log
test-tap/reporters/default.timeoutwithmatch.v14.log
test-tap/reporters/default.timeoutwithmatch.v16.log
test-tap/reporters/default.timeoutwithmatch.v17.log

This PR adds a line in test summary to indicate the number of tests that failed due to timeout. Fixes #2639.
> 5 tests remained pending after a timeout
I have modified `stats.timeout` to represent the number of timed-out tests. I couldn't find what `stats.timeout` was supposed to represent but I changed it to what I expect from it by looking at the context.
```diff
diff --git a/lib/run-status.js b/lib/run-status.js
index a18f4e1af..b6128cda7 100644
--- a/lib/run-status.js
+++ b/lib/run-status.js
@@ -125,7 +125,10 @@ export default class RunStatus extends Emittery {
case 'timeout':
event.pendingTests = this.pendingTests;
this.pendingTests = new Map();
-				stats.timeouts++;
+				for (const [, testsInFile] of event.pendingTests.entries()) {
+					stats.timeouts += testsInFile.size;
+				}
+ …
```

Add number of timeouts in test summary

---

.github/workflows/ci.yml

Update the hashing algorithm used for the `package-lock.json` checksum in the CI from MD5 to SHA512 - the same algorithm used by npm for the integrity check in the `package-lock.json` file itself.
My motivation for doing this is that MD5 is considered an insecure hash algorithm nowadays (ref. [the MD5 Wikipedia page](https://en.wikipedia.org/wiki/MD5) or [RFC 6151](https://datatracker.ietf.org/doc/html/rfc6151)). I do not intend to start a discussion on whether that's relevant in this particular case. I believe that regardless of ones point of view on the matter, upgrading to SHA512 is harmless (considering that this project is already using SHA512 through the lockfile).

Replace md5sum with sha512sum

---

docs/recipes/debugging-with-vscode.md

Fix issue #2946 where VSCode was no longer debugging ava tests using binstub installed by npm.
Changing the script to call directly cli.mjs worked for some users with this problem on windows.

VSCode debug documentation fix

---

docs/01-writing-tests.md
docs/recipes/test-setup.md

This removes the mentions of "callback mode" from the documentation, following the removal of "callback mode" in [v4.0.0 of AVA](https://github.com/avajs/ava/releases/tag/v4.0.0) (see also [this comment](https://github.com/avajs/ava/issues/2929#issuecomment-1162377005)).

Remove mentions of "callback mode" from docs

---

readme.md

Resolves #3026
I added the note to `/readme.md`, instead of to `/docs/08-common-pitfalls.md` as discussed. I did this so I could put it directly under the installation instructions, which seemed the most appropriate place.

Document that AVA 4 cannot be run globally

---

lib/worker/line-numbers.js

When used with `ts-node/register`, we've seen entries without original values. Return the original position.
See `ts.zip` reproduction in https://github.com/avajs/ava/issues/3049#issuecomment-1149431912.

When translating line numbers, check whether the source map entry has original values

---

lib/reporters/default.js
test-tap/reporters/default.edgecases.v12.log
test-tap/reporters/default.edgecases.v14.log
test-tap/reporters/default.edgecases.v16.log
test-tap/reporters/default.edgecases.v18.log

This makes the failure a little less mysterious.
See discussion in https://github.com/avajs/ava/issues/3049.

Report error when parsing for line number selection

---

lib/worker/line-numbers.js

This means the supported syntax changes depending on the installed Acorn version, which may change independently of the AVA version since we do not pin the dependency.

Parse for line numbers with latest supported ECMA version

---

lib/reporters/default.js
lib/run-status.js

This ensures AVA exits with code 1 if any timeout occurs, even if there were no pending tests.
Fixes #3098.

Count timeouts separately from the timed out tests

---

lib/api.js
lib/now-and-timers.cjs
lib/test.js

**I have fixed this issue** : https://github.com/avajs/ava/issues/3060.
Was added constraint for max time of setTimeout.

Cap idle timeouts to the maximum possible value

---

docs/recipes/browser-testing.md

In this PR, I am suggesting to use `jsdom` directly instead of the `browser-env` tool. Even though it is a helpful tool, browser-env hasn't been updated in many years as it seems.
I also believe the suggestions here about writing unit tests for JavaScript in the browser are more explicit, by adding only the necessary globals and DOM elements for the particular test target. I like to see it as a TDD friendly approach 😄

Update to the browser testing recipe to use jsdom directly

---

lib/plugin-support/shared-workers.js
test/shared-workers/multiple-workers-are-loaded/fixtures/package.json
test/shared-workers/multiple-workers-are-loaded/fixtures/test.js
test/shared-workers/multiple-workers-are-loaded/fixtures/worker.mjs
test/shared-workers/multiple-workers-are-loaded/test.js

This fixes the bug introduced in https://github.com/avajs/ava/pull/3149 that I briefly mentioned.
Since we were assigning the launched shared worker to a single variable per test worker, we inadvertently assumed that a test worker would launch a maximum of 1 shared worker.
I tested this patch with two of our internal codebases that heavily use shared workers and everything's working as expected now.
Sorry for the previous buggy PR!

De-register all shared workers

---

test-types/import-in-cts/throws.cts
test-types/module/throws.ts
types/assertions.d.cts

Updates type definitions to infer thrown error type from given expectations.
Writing `const error = t.throws<CustomError>(fn, { instanceOf: CustomError });` felt redundant and I thought there must be a way to infer the error type from the given `instanceOf` expectation. The tricky part was in making inference work for both `instanceOf` and `is` expectations.
I worked it out in [this playground](https://www.typescriptlang.org/play?ts=4.7.4#code/KYDwDg9gTgLgBDAnmYcCiUrQMIQHYDOMUArgMYzQA8GWUAKsqqDMHgCYHqbRwC83OgD5+cAN4BYAFABIPMADucABQA6dQEMoAcwIAuOBryIA2gF0AlAdrRGKANzSZUYBvb4ANojhgslJCjWPAxMjlIAvtLSoJCwCExw9AAWWAoEaODAFBowAJb4NMF2zCCsHFw2ULiExOSUUHAAPoLQIgKSsgD0AFTdiUmoMCkQCnhwwMFwALYkRHBJGgBuqBpwZBDsgwvwwACOJBoeXEOo2rnLY0RQuXjacLx4JFMARhOqcN2dTuubAPwGVxud2ajxeEzCTh6fWSW1SYwmdGms3gr0MYxuRCMZF …

Infer thrown error from expectations

---

lib/cli.js

Currently, the help command/option prints `cli.mjs` as the script name. This PR sets it to `ava` so that it's in line with the [CLI doc](https://github.com/avajs/ava/blob/main/docs/05-command-line.md).

Explicitly configure script name for CLI

---

docs/recipes/typescript.md

adds a recipe to use the `tsx` loader from esbuild
closes #2593;

Update TypeScript recipe to remove ts-node recommendation

---

docs/03-assertions.md
lib/like-selector.js
test-tap/assert.js

Continues from #3023. Adds a test case (the repro from #2627) and handles the `Reflect.ownKeys(array).length` issue.
Fixes #2627.
It's been a couple months since someone last said they'd add this, so I went for it.

Support arrays in t.like() assertion

---

docs/03-assertions.md
lib/like-selector.js
test-tap/assert.js

Update t.like to support Symbol keys and ignore non-enumerable properties

---

lib/like-selector.js
test-tap/assert.js

The previous implementation tracked each object, even if not circular. Update to use a stack.
Fixes #3205.

Fix circular selector detection in t.like()

---

lib/cli.js

This helped recording coverage when testing AVA itself, but hopefully it also helps user projects.

Pro-actively write out code coverage

---

lib/fork.js

Looks like the patch is included in all supported Node.js versions.

Remove workaround for worker.terminate() crashes

---

docs/recipes/typescript.md

Adds info to the TypeScript recipe about potential issues with using `esmock` with `tsx` (https://github.com/esbuild-kit/tsx/issues/264) and using a TypeScript loader in Node.js 20 (https://github.com/avajs/ava/issues/2593#issuecomment-1524846453).

Update TypeScript recipe for mocks, Node.js 20

---

test-types/import-in-cts/assertions-as-type-guards.cts
test-types/module/assertions-as-type-guards.ts
types/assertions.d.cts

This will make ava easier to use with typescript and allow for removing redundant checks.
```ts
// with change
const actual = 3 as number | undefined;
if (t.assert(actual)) {
// actual is `number` here
} else {
// actual is `undefined` here
}
```
```ts
// before change
const actual = 3 as number | undefined;
t.assert(actual);
// Need a separate if branch from the assertion
if (actual) {
// actual is `number` here
} else {
// actual is `undefined` here
}
```
Since ava is a library and to reduce any type errors in existing projects, it's best to use the most exact approach to the typeguards as possible. For most use cases something akin to `actual is NonNullable<T>` is completely valid, but in this case it's very likely that things like `boolean` will be passed in.
Unfortunately typescript …

Make `assert`, `truthy` and `falsy` typeguards

---

docs/03-assertions.md
docs/recipes/typescript.md
lib/assert.js
lib/test.js
test-tap/assert.js
test-tap/fixture/report/regular/traces-in-t-throws.cjs
test-tap/reporters/default.regular.v16.log
test-tap/reporters/default.regular.v18.log
test-tap/reporters/default.regular.v20.log
test-tap/reporters/tap.failfast.v16.log
test-tap/reporters/tap.failfast.v18.log
test-tap/reporters/tap.failfast.v20.log
test-tap/reporters/tap.failfast2.v16.log
test-tap/reporters/tap.failfast2.v18.log
test-tap/reporters/tap.failfast2.v20.log
test-tap/reporters/tap.regular.v16.log
test-tap/reporters/tap.regular.v18.log
test-tap/reporters/tap.regular.v20.log
test-tap/test.js
test-types/import-in-cts/assertions-as-type-guards.cts
test-types/import-in-cts/throws.cts
test-types/module/assertions-as-type-guards.ts
test-types/module/snapshot.ts
test-types/module/throws.ts
types/assertions.d.cts

Fixes https://github.com/avajs/ava/issues/3201.
Assertions now throw a `TestFailure` error when they fail. This error is not exported or documented and should not be used or thrown manually. You cannot catch this error in order to recover from a failure, use `t.try()` instead.
All assertions except for `throws` and `throwsAsync` now return `true` when they pass. This is useful for some of the assertions in TypeScript where they can be used as a type guard.
Committing a failed `t.try()` result now also throws.

Make assertions throw

---

scripts/ci.sh

These tests are more likely to be flaky on Mac and Windows.

ci: Only test reporters on Linux

---

ava.config.js
lib/watcher.js
package-lock.json
scripts/ci.sh
test/watch-mode/helpers/watch.js

- Ensure watcher tests exit cleanly
- Test with AVA 6

Test with AVA 6

---

lib/api.js

Don't emit the 'touched-files' event, since the watcher assumes that comes with a files value.
Fixes #3285

Fix potential bug with watch mode when no failed test files are written

---

docs/01-writing-tests.md
docs/07-test-timeouts.md
docs/08-common-pitfalls.md
entrypoints/main.d.mts
entrypoints/main.mjs
lib/run-status.js
lib/worker/base.js
lib/worker/completion-handlers.js
lib/worker/state.cjs
test/completion-handlers/fixtures/exit0.js
test/completion-handlers/fixtures/one.js
test/completion-handlers/fixtures/package.json
test/completion-handlers/fixtures/two.js
test/completion-handlers/test.js

Register a function to be called when AVA has completed a test run without uncaught exceptions or unhandled rejections.
Fixes #3279.

Implement registerCompletionHandler()

---

entrypoints/internal.d.mts

We finally started building on top of the API [I added last year](https://github.com/avajs/ava/pull/3247) and discovered a small typo. The `ava/internal` type import was failing until I made this change.

Fix import typo

---

docs/recipes/typescript.md

Loaders must be added via the new `--import` flag (previously, `--loader` was used). The updated recipe recommends `tsimp`[^1], per https://github.com/avajs/ava/discussions/3213#discussioncomment-8085427.
I added a table of supported Node.js versions for the `--import` flag, but they should probably be double checked. I also removed the section about mocking, since `tsimp` seems to work without issue.
[^1]: [npm](https://www.npmjs.com/package/tsimp), [GitHub](https://github.com/tapjs/tsimp)

Update TypeScript recipe for loader changes

---

.xo-config.cjs
examples/macros/test.js
examples/timeouts/test.js
lib/cli.js
lib/create-chain.js
lib/eslint-plugin-helper-worker.js
lib/load-config.js
lib/plugin-support/shared-worker-loader.js
lib/snapshot-manager.js
lib/test.js
lib/watcher.js
package-lock.json
package.json
test-tap/api.js
test-tap/assert.js
test-tap/code-excerpt.js
test-tap/reporters/tap.regular.v18.log
test-tap/reporters/tap.regular.v20.log
test-tap/reporters/tap.regular.v21.log
test/helpers/exec.js

Disabled `unicorn/prevent-abbreviations` because it introduces too many opinionated changes.

Upgrade `xo` to `v0.57.0` and lint sources, tests, and examples

---

lib/assert.js
test-tap/assert.js

Update t.throws to accept falsy non-Error thrown values when expectation.any is true

---

docs/06-configuration.md

all CLI options can be overridden but this one was omitted https://github.com/avajs/ava/blob/01ec2804ab9db0ab3ef11e3b5b0c5697d68f8bc5/lib/cli.js#L58-L63
I confirmed in code that it is observed
https://github.com/avajs/ava/blob/01ec2804ab9db0ab3ef11e3b5b0c5697d68f8bc5/lib/cli.js#L438
It wasn't clear to me what order to use so I put it before `tap` as it is in `cli.js`.
I'd suggest partitioning the options list into ones that are available in CLI and aren't, but I didn't know if that would be welcomed

docs: add `serial` to config options

---

docs/recipes/watch-mode.md
lib/api.js
lib/runner.js
lib/watcher.js
lib/worker/base.js
test-tap/runner.js
test/watch-mode/scenarios.js

This is a historical feature back from when AVA tried to persist "runExclusive" during regular runs. This behavior
conflicts with interactive mode, and in any case interactive mode makes it easier to focus on a specific test file or
title.
Originally part of https://github.com/avajs/ava/pull/3372/ but it's a significant enough change that it deserves to be its own PR.
Still, should ship alongside those changes.

Remove special .only() behavior in watch mode

---

.github/workflows/ci.yml
.github/workflows/release.yml
maintaining.md

- **Add Release workflow**
- **Update maintaining.md**
- **Attempt to make Release workflow dependent on CI checks, with a manual trigger if necessary**

Update release process & maintaining notes

---

.github/workflows/release.yml
maintaining.md

- **Verify release commit is in the main branch**
- **Improve CI status check**
- **Execute package.json check within jq**
- **Perform package.json check first**
- **Update instructions**

Release process tweaks

---

lib/fork.js
lib/worker/base.js
lib/worker/channel.cjs
test/child-process/fixtures/package.json
test/child-process/fixtures/test.js
test/child-process/test.js

This change ensures that all messages from the worker are received by the main process before the worker exits.
It solves issues on Windows that are occurring with Node.js v20 and later when `workerThreads: false` is set in the AVA configuration.
Fixes: https://github.com/avajs/ava/issues/3390

Keep test worker alive until explicitly freed
